spring:
  application:
    name: "master-data-calendar-uservice"
    version: 1.0
    title: "Master Data Calendar Service"
    description: "Master data calendar service"
  main:
    allow-bean-definition-overriding: true
server:
  port: 7321
  tomcat:
    max-connections: 500
    threads:
      min-spare: 50
      max: 200

constants:
  defaultNumberOfDaysInFuture: 10

logging:
  level:
    org.springframework: WARN
    root: INFO

