spring:
  application:
    name: "pe-promise-sourcing-rule-uservice"
    version: ${version}
    title: "Promise Sourcing Rule Service"
    description: "Promising and sourcing rule service"
    properties:
      group: promising-and-sourcing
      customerFacing: false
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080
  tomcat:
    max-connections: 500
    threads:
      min-spare: 50
      max: 200

logging:
  level:
    org.springframework: WARN
    root: WARN
    com.nextuple: INFO
entity-listener:
  kafka:
    enabled: true
promise:
  service:
    options: "SDND,STANDARD,EXPRESS,NEXTDAY"
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: false
    metrics:
      enabled: true
    loggers:
      enabled: true
  metrics:
    export:
#      newrelic:
#        enabled: true
#        api-key: \${NEW_RELIC_API_KEY}
#        account-id: \${NEW_RELIC_ACCOUNT_ID}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
        persistence: true
        cache: true
  prometheus.metrics.export.enabled: false
#pe:
#  ui:
#    allowed-origin-url: \${PE_UI_URL}
feign:
  okhttp:
    enabled: true
auth:
  filterEnabled: false
base-api-url: '/promising-engine/pe-promise-sourcing-rule'
holiday-cutoff:
  days: 0.0
  days-type: BUSINESS_DAYS