spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://promise-engine-postgres-performance.cluster-co9l0bkmgaei.us-east-1.rds.amazonaws.co/pe
    username: \${POSTGRES_USER}
    password: \${POSTGRES_PWD}
  replica:
    datasource:
      platform: postgres
      url: jdbc:postgresql://promise-engine-postgres-performance.cluster-ro-co9l0bkmgaei.us-east-1.rds.amazonaws.com,promise-engine-postgres-performance.cluster-co9l0bkmgaei.us-east-1.rds.amazonaws.co/pe?readOnly=true
      username: \${POSTGRES_USER}
      password: \${POSTGRES_PWD}
      required: true
      hikari:
        readOnly: true

logging:
  level:
    root: WARN
    com.hbc: INFO
auth:
  issuer: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_SJ1yMwanC