spring:
  config:
    import: optional:aws-secretsmanager:/secret/promise-\${SPRING_PROFILES_ACTIVE}
  application:
    name: "promising-sourcing-rule"
    version: 1.0
    title: "Promising Sourcing Rule Service"
    description: "Promising Sourcing Rule Service"
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        generate_statistics: true
server:
  port: 8080
  tomcat:
    max-connections: 500
    threads:
      min-spare: 50
      max: 200

aws:
  s3:
    signed-url-expiry-minutes: 30
storage:
  type: S3

logging:
  level:
    org.springframework: WARN
    root: WARN
    com.hbc: INFO

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: false
    metrics:
      enabled: true
    loggers:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: false
      newrelic:
        enabled: true
        api-key: \${NEW_RELIC_API_KEY}
        account-id: \${NEW_RELIC_ACCOUNT_ID}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
        persistence: true
        cache: true
entity-listener:
  kafka:
    enabled: true
pe:
  ui:
    allowed-origin-url: \${PE_UI_URL}
