options:
  docker: true
image: openjdk:11
clone:
  depth: full
server:
  service:
    name: "pe-masterdata-uservice"
    path:
      - promising-engine/pe-node-masterdata
      - promising-engine/pe-item-masterdata
      - promising-engine/pe-data-upload-masterdata
      - promising-engine/pe-promise-sourcing-rule-masterdata
      - promising-engine/pe-weightage-configuration-masterdata
      - promising-engine/pe-postal-code-timezone-masterdata
      - promising-engine/pe-transit-masterdata
      - promising-engine/pe-node-carrier-masterdata
      - promising-engine/pe-calendar-masterdata
      - promising-engine/pe-carrier-masterdata
    health-check-endpoint: "/actuator/health"
  environments:
    vapt:
      ingress: yes
      middleman: yes
      prometheus: yes
      keyvault: yes
      storage: yes
      scale:
        replicas: 2
      resources:
        min:
          memory: "1024Mi"
          cpu: 256m
        max:
          memory: "1024Mi"
          cpu: 256m
    prod:
      ingress: yes
      middleman: yes
      prometheus: yes
      keyvault: yes
      storage: yes
      scale:
        replicas: 2
      resources:
        min:
          memory: "1024Mi"
          cpu: "500m"
        max:
          memory: "1024Mi"
          cpu: "500m"
    test:
      ingress: yes
      middleman: yes
      prometheus: yes
      keyvault: yes
      storage: yes
      scale:
        replicas: 2
      resources:
        min:
          memory: "1024Mi"
          cpu: 256m
        max:
          memory: "1024Mi"
          cpu: 256m
    dev:
      ingress: yes
      middleman: yes
      prometheus: yes
      storage: yes
      keyvault: yes
      scale:
        replicas: 1
      resources:
        min:
          memory: "1024Mi"
          cpu: 256m
        max:
          memory: "1024Mi"
          cpu: 256m
    qa:
      ingress: yes
      middleman: yes
      prometheus: yes
      storage: yes
      keyvault: yes
      scale:
        replicas: 1
      resources:
        min:
          memory: 1024Mi
          cpu: 256m
        max:
          memory: 1024Mi
          cpu: 256m
    sandbox:
      ingress: yes
      middleman: yes
      prometheus: yes
      keyvault: yes
      storage: yes
      scale:
        replicas: 1
      resources:
        min:
          memory: 1024Mi
          cpu: 256m
        max:
          memory: 1024Mi
          cpu: 256m
definitions:
  caches:
    sonar: ~/.sonar/cache
    cve: ~/.cve
  steps:
    - step: &build
        name: Build Snapshot
        caches:
          - gradle
          - sonar
        script:
          - git clone git@bitbucket.org:nextuple_engineering/infra-automation.git
          - cp ./infra-automation/suppressions.xml ./suppressions.xml
          - bash ./gradlew -Pbuild_target=SNAPSHOT clean build artifactoryPublish
          - export SPACE=" "
          - bash ./gradlew -Pbuild_target=SNAPSHOT -q properties | grep version | sed -e "s@version:$SPACE@@g" > service-version.txt
        artifacts:
          - build/**
          - service-version.txt
    - step: &build-qa
        name: Build QA
        caches:
          - gradle
          - sonar
        script:
          - bash ./gradlew -Pbuild_target=QA clean build --refresh-dependencies artifactoryPublish
          - export SPACE=" "
          - bash ./gradlew -Pbuild_target=QA -q properties | grep version | sed -e "s@version:$SPACE@@g" > service-version.txt
        artifacts:
          - build/**
          - service-version.txt
    - step: &build-stage
        name: Build Stage
        caches:
          - gradle
        script:
          - bash ./gradlew -Pbuild_target=STAGED clean build artifactoryPublish
          - export SPACE=" "
          - bash ./gradlew -Pbuild_target=STAGED -q properties | grep version | sed -e "s@version:$SPACE@@g" > service-version.txt
        artifacts:
          - build/**
          - service-version.txt
    - step: &build-release
        name: Build Release
        script:
          - echo "Pre Deploy Step"
    - step: &deploy
        caches:
          - gradle
        services:
          - docker
        image: mcr.microsoft.com/azure-cli
        script:
          - git clone git@bitbucket.org:nextuple_engineering/deployment-scripts.git
          - chmod +x ./deployment-scripts/deploy-k8s-service-v7.sh
          - ./deployment-scripts/deploy-k8s-service-v7.sh
        after-script:
          - chmod +x ./deployment-scripts/after-deploy-k8s-service-v3.sh
          - ./deployment-scripts/after-deploy-k8s-service-v3.sh
    - step: &pr-build
        name: PR Build
        caches:
          - gradle
          - sonar
          - cve
        script:
          - git clone git@bitbucket.org:nextuple_engineering/infra-automation.git
          - cp ./infra-automation/suppressions.xml ./suppressions.xml
          - bash ./gradlew -Pbuild_target=SNAPSHOT clean build jacocoTestReport spotbugsMain
          - bash ./gradlew dependencyCheckAggregate --info
          - bash ./gradlew sonarqube showSonarQubeLink --info
pipelines:
  pull-requests:
    '**':
      - step: *pr-build
  tags:
    '*-SNAPSHOT':
      - step: *build
      - step:
          !!merge <<: *deploy
          name: Deploy Dev
          deployment: dev
      - step:
          !!merge <<: *deploy
          name: Deploy QA
          trigger: manual
          deployment: qa
      - step:
          !!merge <<: *deploy
          name: Deploy Test
          trigger: manual
          deployment: test
      - step:
          !!merge <<: *deploy
          name: Deploy Demo
          trigger: manual
          deployment: demo
    '*-SANDBOX':
      - step: *build-release
      - step:
          !!merge <<: *deploy
          name: Deploy Sandbox
          deployment: sandbox
    '*-RELEASE':
      - step: *build-release
      - step:
          !!merge <<: *deploy
          name: Deploy Prod
          trigger: manual
          deployment: prod
  branches:
    vapt:
      - step: *build
      - step:
          !!merge <<: *deploy
          name: Deploy vapt
          deployment: vapt
    monolith-modular-development:
      - step: *build
      - step:
          !!merge <<: *deploy
          name: Deploy Dev
          deployment: dev
      - step:
          !!merge <<: *deploy
          name: Deploy QA
          trigger: manual
          deployment: qa
      - parallel:
          - step:
              !!merge <<: *deploy
              name: Deploy Test
              trigger: manual
              deployment: test
          - step:
              !!merge <<: *deploy
              name: Deploy Demo
              trigger: manual
              deployment: demo
    master:
      - step: *build-release
      - step:
          !!merge <<: *deploy
          name: Deploy Prod
          trigger: manual
          deployment: prod
