spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://postgresql00-nonprod-wu2.nextuple.net:5432/pe
    username: \${COMMON-PE-POSTGRES-USER}
    password: \${COMMON-PE-POSTGRES-PASSWORD}
  flyway:
    enabled: false
  kafka:
    bootstrap-servers: "kbrk-nonprod.nextuple.net:9092"
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: \${COMMON-KAFKA-CONFIG}
    consumer-retry-count: 1
    # NOTE: Below commented code is for the Avro consumer.
    # If we need to consume an avro record, please uncomment Avro properties and comment out the JSON Consumer and Producer.
    #
    #    consumer:
    #      type: avro
    #      enable-auto-commit: true
    #      auto-offset-reset: latest
    #      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #      value-deserializer: com.nextuple.item.consumer.serializer.ItemDeserializer
    #      topics:
    #        item_master:
    #          name: INTERNAL.DEV.PROMISE_ITEMS
    #          group-id: item-master-dev
    #    producer:
    #      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    #      value-serializer: com.nextuple.item.consumer.serializer.ItemSerializer
    consumer-item:
      type: json
      enable-auto-commit: true
      auto-offset-reset: latest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring-deserializer-key-delegate-class: org.apache.kafka.common.serialization.StringDeserializer
        spring-deserializer-value-delegate-class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring-json-trusted-packages: "*"
        spring-json-type-mapping: com.nextuple.pe.webhook.domain.dtos.Item:com.nextuple.item.domain.events.ItemMasterEvent
        interceptor.classes: "com.nextuple.common.interceptor.KafkaConsumerContextInterceptor"
      topics:
        item_master:
          name: INTERNAL.DEV.PROMISE_ITEMS
          group-id: item-master-dev-\${random.value}
    producer-item:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.nextuple.item.consumer.serializer.JsonSerializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      topics:
        master_data_update_event: INTERNAL.DEV.MASTER_DATA_UPDATE_EVENTS
      properties:
        acks: 1
        retries: 5
        retry.backoff.ms: 1000
        spring.json.trusted.packages: "*"
        interceptor.classes: "com.nextuple.common.interceptor.KafkaProducerContextInterceptor"
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        interceptor.classes: "com.nextuple.common.interceptor.KafkaConsumerContextInterceptor"
        max.poll.records: 10
      topics:
        master_data_update_event:
          name: INTERNAL.DEV.MASTER_DATA_UPDATE_EVENTS
          group-id: master-data-update-dev
    consumer-string:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      key-delegate-class: org.apache.kafka.common.serialization.StringDeserializer
      trusted-packages: "*"
      interceptor-classes: "com.nextuple.common.interceptor.KafkaConsumerContextInterceptor"
      enable-auto-commit: true
      auto-offset-reset: latest

logging:
  level:
    com.nextuple: INFO
pe-public-webhook:
  iv-feed:
    topic: INTERNAL.DEV_ATP
  item-feed:
    topic: INTERNAL.DEV.PROMISE_ITEMS
  pe-response:
    topic: INTERNAL.DEV.CART_EDD
    group-id: pe-response-consumer-dev-async
  webhook:
    - tenantId: NEXTUPLE_GR
      moduleName: PROMISING
      webhookName: PROMISING_INTERMEDIATE_EVENT
      webhookDetail:
        endpoint: "https://dc5647e2-a0d6-436b-bfba-6097594abe60.mock.pstmn.io"
        method: POST
        headers:
          contentType: "application/json"
          x-api-key: "PMAK-649a7ee4b2aa120030dfba82-4fe9121cae4c8059978d6e49f996cbefeb"
          #          Dummy API Key
    - tenantId: XYZINC
      moduleName: PROMISING
      webhookName: PROMISING_INTERMEDIATE_EVENT
      webhookDetail:
        endpoint: "https://dc5647e2-a0d6-436b-bfba-6097594abe60.mock.pstmn.io"
        method: POST
        headers:
          contentType: "application/json"
          x-api-key: "PMAK-649a7ee4b2aa120030dfba82-4fe9121cae4c8059978d6e49f996cbefeb"
          #          Dummy API Keydataupload:
dataupload:
  type: IBM-S3
  signed-url-expiry-minutes: 30
  maxsize-in-kilobytes: 10240
  max-rows: 1000
  bucket-name: "pe-data-upload"
  azure:
    base-path: "https://pedataupload.blob.core.windows.net"
    bucket-name: "dataupload"
    type: BLOB
  ibm:
    base-path: "https://s3.us-east.cloud-object-storage.appdomain.cloud"
    bucket-name: "pe-data-upload"
    type: IBM-S3
    access-key: "7d282782c4cd4ea0905483416e0bdbd9"  #\${COMMON-ACCESS_KEY}
    secret-key: "c811f5f47fb126f24fdc90c4e60bbaf1d22b383553d61b99" #\${COMMON-SECRET_KEY}

jobs-framework:
  job-completion-consumer:
    topic-name: INTERNAL.DEV.PE.JOB_COMPLETION
    group-id: jobs-completion-consumer-async-dev
  kafka-publish:
    topic-name: INTERNAL.DEV.PE.JOB_TASK
  result-publish:
    topic-name: INTERNAL.DEV.PE.JOB_RESULT
  result-consumer:
    topic-name: INTERNAL.DEV.PE.JOB_RESULT
    group-id: jobs-result-consumer-async
  record-consumer:
    topic-name: INTERNAL.DEV.PE.JOB_TASK
    group-id: jobs-task-consumer-async

master-data:
  node:
    topic-name: INTERNAL.DEV.PE.NODE_INTEGRATION
    group-id: node-master-dev
  node-carrier:
    topic-name: INTERNAL.DEV.PE.NODE_CARRIER_INTEGRATION
    group-id: node-carrier-master-dev
  carrier:
    topic-name: INTERNAL.DEV.PE.CARRIER_INTEGRATION
    group-id: carrier-master-dev
  processing-lead-time:
    topic-name: INTERNAL.DEV.PE.PROCESSING_LEAD_TIME_INTEGRATION
    group-id: processing-lead-time-master-dev
  calendar:
    topic-name: INTERNAL.DEV.PE.CALENDAR_INTEGRATION
    group-id: calendar-master-dev
  node-calendar:
    topic-name: INTERNAL.DEV.PE.NODE_CALENDAR_INTEGRATION
    group-id: node-calendar-master-dev
  carrier-service-calendar:
    topic-name: INTERNAL.DEV.PE.CARRIER_SERVICE_CALENDAR_INTEGRATION
    group-id: carrier-service-calendar-master-dev
  pickup-calendar:
    topic-name: INTERNAL.DEV.PE.PICKUP_CALENDAR_INTEGRATION
    group-id: pickup-calendar-master-dev
  node-service-option-buffer:
    topic-name: INTERNAL.DEV.PE.NODE_SERVICE_OPTION_BUFFER_INTEGRATION
    group-id: node-service-option-buffer-master-dev
  transit:
    topic-name: INTERNAL.DEV.PE.TRANSIT_INTEGRATION
    group-id: transit-master-dev
  transit-buffer:
    topic-name: INTERNAL.DEV.PE.TRANSIT_BUFFER_INTEGRATION
    group-id: transit-buffer-master-dev

next-cache:
  caches:
    -
      cacheName: task-info
      ttlSeconds: 14400
      maxLimit: 50
  refresh-cache:
    topic: INTERNAL.DEV.PE.REFRESH_CACHE_INV
  cacheManager: caffeine
platform:
  tasks:
    enabled: true
  tasks-scheduler:
    enabled: true
    milliseconds: 5000
  authFilter:
    enabled: false
kafka:
  input:
    taskTopics: INTERNAL.DEV.PE.RETRY_TOPIC_INV
    taskGroupId: pe-retry