spring:
  security:
    oauth2:
      client:
        registration:
          my-client:
            client-id: applicationclient-pe-masterdata-uservice
            client-secret: \${MASTER-DATA-KEYCLOAK-CLIENT-ID}
            authorization-grant-type: client_credentials
            scope: applicationclient-pe-masterdata-scope
        provider:
          my-client:
            token-uri: https://keycloak-nonprod.nextuple.com/realms/noms-dev/protocol/openid-connect/token
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://postgresql00-nonprod-wu2.nextuple.net:5432/pe_integration
    username: \${COMMON-PE-POSTGRES-USER}
    password: \${COMMON-PE-POSTGRES-PASSWORD}
  flyway:
    enabled: false
  kafka:
    bootstrap-servers: "kbrk-nonprod.nextuple.net:9092"
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: \${COMMON-KAFKA-CONFIG}
    consumer-retry-count: 1
    # NOTE: Below commented code is for the Avro consumer.
    # If we need to consume an avro record, please uncomment Avro properties and comment out the JSON Consumer and Producer.
    #
    #    consumer:
    #      type: avro
    #      enable-auto-commit: true
    #      auto-offset-reset: latest
    #      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #      value-deserializer: com.nextuple.item.consumer.serializer.ItemDeserializer
    #      topics:
    #        item_master:
    #          name: INTERNAL.DEV.PROMISE_ITEMS
    #          group-id: item-master-dev
    #    producer:
    #      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    #      value-serializer: com.nextuple.item.consumer.serializer.ItemSerializer
    consumer-item:
      type: json
      enable-auto-commit: true
      auto-offset-reset: latest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring-deserializer-key-delegate-class: org.apache.kafka.common.serialization.StringDeserializer
        spring-deserializer-value-delegate-class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring-json-trusted-packages: "*"
        spring-json-type-mapping: com.nextuple.pe.webhook.domain.dtos.Item:com.nextuple.item.domain.events.ItemMasterEvent
        interceptor.classes: "com.nextuple.common.interceptor.KafkaConsumerContextInterceptor"
      topics:
        item_master:
          names: INTERNAL.INTEGRATION.PROMISE_ITEMS
          group-id: item-master-integration-\${random.value}
    producer-item:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.nextuple.item.consumer.serializer.JsonSerializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      topics:
        master_data_update_event: INTERNAL.INTEGRATION.MASTER_DATA_UPDATE_EVENTS
      properties:
        acks: 1
        retries: 5
        retry.backoff.ms: 1000
        spring.json.trusted.packages: "*"
        interceptor.classes: "com.nextuple.common.interceptor.KafkaProducerContextInterceptor"
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        interceptor.classes: "com.nextuple.common.interceptor.KafkaConsumerContextInterceptor"
        max.poll.records: 10
      topics:
        master_data_update_event:
          name: INTERNAL.INTEGRATION.MASTER_DATA_UPDATE_EVENTS
          group-id: master-data-update-integration
    consumer-string:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      key-delegate-class: org.apache.kafka.common.serialization.StringDeserializer
      trusted-packages: "*"
      interceptor-classes: "com.nextuple.common.interceptor.KafkaConsumerContextInterceptor"
      enable-auto-commit: true
      auto-offset-reset: latest
  sql.init.platform: postgres

logging:
  level:
    com.nextuple: INFO
pe-public-webhook:
  iv-feed:
    topic: INTERNAL.INTEGRATION_ATP
  item-feed:
    topic: INTERNAL.INTEGRATION.PROMISE_ITEMS
  pe-response:
    topics: INTERNAL.INTEGRATION.CART_EDD
    group-id: pe-response-consumer-integration-async
  webhook:
    - tenantId: NEXTUPLE_GR
      moduleName: PROMISING
      webhookName: PROMISING_INTERMEDIATE_EVENT
      webhookDetail:
        endpoint: "https://dc5647e2-a0d6-436b-bfba-6097594abe60.mock.pstmn.io"
        method: POST
        headers:
          contentType: "application/json"
          x-api-key: "PMAK-649a7ee4b2aa120030dfba82-4fe9121cae4c8059978d6e49f996cbefeb"
          #          Dummy API Key
    - tenantId: XYZINC
      moduleName: PROMISING
      webhookName: PROMISING_INTERMEDIATE_EVENT
      webhookDetail:
        endpoint: "https://dc5647e2-a0d6-436b-bfba-6097594abe60.mock.pstmn.io"
        method: POST
        headers:
          contentType: "application/json"
          x-api-key: "PMAK-649a7ee4b2aa120030dfba82-4fe9121cae4c8059978d6e49f996cbefeb"
          #          Dummy API Keydataupload:
dataupload:
  base-path: "https://pedataupload.blob.core.windows.net"
  maxsize-in-kilobytes: 10240
  max-rows: 1000
  bucket-name: "dataupload"
  type: BLOB
  signed-url-expiry-minutes: 30

jobs-framework:
  feed-metrics-consumer:
    topic-name: INTERNAL.INTEGRATION.PE_JOB_FPM_METRICS, INTERNAL.INTEGRATION.PE_JOB_RECORD_FPM_METRICS, INTERNAL.INTEGRATION.PE_NEIP_FPM_METRICS
    group-id: pe-fpm-metrics-integration
  job-completion-consumer:
    topic-name: INTERNAL.INTEGRATION.PE.JOB_COMPLETION
    group-id: jobs-completion-consumer-async-integration
  kafka-publish:
    topic-name: INTERNAL.INTEGRATION.PE.JOB_TASK
  result-publish:
    topic-name: INTERNAL.INTEGRATION.PE.JOB_RESULT
  result-consumer:
    topic-name: INTERNAL.INTEGRATION.PE.JOB_RESULT
    group-id: jobs-result-consumer-async
  record-consumer:
    topic-names: INTERNAL.INTEGRATION.PE.JOB_TASK
    group-id: jobs-task-consumer-async

master-data:
  node:
    topic-names: INTERNAL.INTEGRATION.PE.NODE_INTEGRATION
    group-id: node-master-integration
  node-carrier:
    topic-names: INTERNAL.INTEGRATION.PE.NODE_CARRIER_INTEGRATION
    group-id: node-carrier-master-integration
  carrier:
    topic-names: INTERNAL.INTEGRATION.PE.CARRIER_INTEGRATION
    group-id: carrier-master-integration
  processing-lead-time:
    topic-names: INTERNAL.INTEGRATION.PE.PROCESSING_LEAD_TIME_INTEGRATION
    group-id: processing-lead-time-master-integration
  calendar:
    topic-names: INTERNAL.INTEGRATION.PE.CALENDAR_INTEGRATION
    group-id: calendar-master-integration
  node-calendar:
    topic-names: INTERNAL.INTEGRATION.PE.NODE_CALENDAR_INTEGRATION
    group-id: node-calendar-master-integration
  carrier-service-calendar:
    topic-names: INTERNAL.INTEGRATION.PE.CARRIER_SERVICE_CALENDAR_INTEGRATION
    group-id: carrier-service-calendar-master-integration
  pickup-calendar:
    topic-names: INTERNAL.INTEGRATION.PE.PICKUP_CALENDAR_INTEGRATION
    group-id: pickup-calendar-master-integration
  node-service-option-buffer:
    topic-names: INTERNAL.INTEGRATION.PE.NODE_SERVICE_OPTION_BUFFER_INTEGRATION
    group-id: node-service-option-buffer-master-integration
  transit:
    topic-names: INTERNAL.INTEGRATION.PE.TRANSIT_INTEGRATION
    group-id: transit-master-integration
  transit-buffer:
    topic-names: INTERNAL.INTEGRATION.PE.TRANSIT_BUFFER_INTEGRATION
    group-id: transit-buffer-master-integration
  transfer-schedule:
    topic-names: INTERNAL.INTEGRATION.PE.TRANSFER_SCHEDULES
    group-id: transfer-schedules-master-integration
  item:
    dlt-topic: ITEM_MASTER_INTEGRATION.DLT

next-cache:
  caches:
    -
      cacheName: task-info
      ttlSeconds: 14400
      maxLimit: 50
  refresh-cache:
    topic: INTERNAL.INTEGRATION.PE.REFRESH_CACHE_INV
  cacheManager: caffeine
platform:
  tasks:
    enabled: true
  tasks-scheduler:
    enabled: true
    milliseconds: 5000
  authFilter:
    enabled: false
neo-platform:
  auth-injector:
    token-strategy: generate
    filter:
      enabled: true
    client-uri-mappings:
      my-client: /**
  auth-validator:
    application-name: pe-masterdata
    header:
      tenant-id: x-tenant-id
    issuer-uri: https://keycloak-nonprod.nextuple.com/realms/noms-dev
    authz-config:
      config-path: "http://plt-authz-config-uservice:8080/api/configurations/groups/application-group/scope-id/pe-masterdata"
      refresh-interval-mins: 30
      role:
        json-paths: \$.resource_access.tenantclient-nextuple.roles,\$.resource_access.tenantclient-kohls.roles,\$.resource_access.tenantclient-xyzinc.roles,\$.resource_access.tenantclient-abcinc.roles,\$.resource_access.tenantclient-neednow.roles,\$.resource_access.tenantclient-ctppt.roles,\$.resource_access.applicationclient-pe-masterdata-uservice.roles,\$.resource_access.applicationclient-pe-core-uservice.roles,\$.resource_access.applicationclient-pe-iv-cache.roles,\$.resource_access.applicationclient-pe-capacity-uservice.roles,\$.resource_access.applicationclient-pe-neip-uservice.roles
kafka:
  input:
    taskTopics: INTERNAL.INTEGRATION.PE.RETRY_TOPIC_INV
    taskGroupId: pe-retry

kafka-topic-flags:
  item-master:
    enabled: true
  master_data_update_event:
    enabled: true
  jobs-framework:
    feed-metrics-consumer:
      enabled: true
    job-completion-consumer:
      enabled: true
    kafka-publish:
      enabled: true
    result-publish:
      enabled: true
    result-consumer:
      enabled: true
    record-consumer:
      enabled: true
  pe-public-webhook:
    iv-feed:
      enabled: true
    item-feed:
      enabled: true
    pe-response:
      enabled: true
  master-data:
    node:
      enabled: true
    node-carrier:
      enabled: true
    carrier:
      enabled: true
    processing-lead-time:
      enabled: true
    calendar:
      enabled: true
    node-calendar:
      enabled: true
    carrier-service-calendar:
      enabled: true
    pickup-calendar:
      enabled: true
    node-service-option-buffer:
      enabled: true
    transit:
      enabled: true
    transit-buffer:
      enabled: true
    transfer-schedule:
      enabled: true
  refresh-cache:
    enabled: true
  input:
    taskTopics:
      enabled: true