spring:
  security:
    oauth2:
      client:
        registration:
          my-client:
            client-id: applicationclient-pe-masterdata-uservice
            client-secret: \${MASTER-DATA-KEYCLOAK-CLIENT-ID}
            authorization-grant-type: client_credentials
            scope: applicationclient-pe-masterdata-scope
        provider:
          my-client:
            token-uri: https://keycloak-nonprod.nextuple.com/realms/noms-dev/protocol/openid-connect/token
  application:
    dependencies:
      item: "http://localhost:8080/"
      node-carrier: "http://localhost:8080/"
      carrier: "http://localhost:8080/"
      transit: "http://localhost:8080/"
      data-upload: "http://localhost:8080/"
      node: "http://localhost:8080/"
      promise-sourcing-rule: "http://localhost:8080/"
      calendar: "http://localhost:8080/"
      postal-code-timezone: "http://localhost:8080/"
      weightage-configuration: "http://localhost:8080/"
      userexit: "http://localhost:8080/"
      configuration: "http://localhost:8080/"
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    hikari:
      maximumPoolSize: 100
      minimumIdle: 10
  flyway:
    enabled: false
  kafka:
    bootstrap-servers: "localhost:9092"
    properties:
      security.protocol: PLAINTEXT
      sasl.mechanism: NA
      sasl.jaas.config: NA
    consumer-retry-count: 1
    # NOTE: Below commented code is for the Avro consumer.
    # If we need to consume an avro record, please uncomment Avro properties and comment out the JSON Consumer and Producer.
    #
    #    consumer:
    #      type: avro
    #      enable-auto-commit: true
    #      auto-offset-reset: latest
    #      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #      value-deserializer: com.nextuple.item.consumer.serializer.ItemDeserializer
    #      topics:
    #        item_master:
    #          name: INTERNAL.DEV.PROMISE_ITEMS
    #          group-id: item-master-dev
    #    producer:
    #      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    #      value-serializer: com.nextuple.item.consumer.serializer.ItemSerializer
    consumer-item:
      type: json
      enable-auto-commit: true
      auto-offset-reset: latest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring-deserializer-key-delegate-class: org.apache.kafka.common.serialization.StringDeserializer
        spring-deserializer-value-delegate-class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring-json-trusted-packages: "*"
        spring-json-type-mapping: com.nextuple.pe.webhook.domain.dtos.Item:com.nextuple.item.domain.events.ItemMasterEvent
        interceptor.classes: "com.nextuple.common.interceptor.KafkaConsumerContextInterceptor"
      topics:
        item_master:
          names: ITEM_MASTER_INTEGRATION
          group-id: item-master-local
    producer-item:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.nextuple.item.consumer.serializer.JsonSerializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
        acks: 1
        interceptor.classes: "com.nextuple.common.interceptor.KafkaProducerContextInterceptor"
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        interceptor.classes: "com.nextuple.common.interceptor.KafkaConsumerContextInterceptor"
        max.poll.records: 10
    consumer-string:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      key-delegate-class: org.apache.kafka.common.serialization.StringDeserializer
      trusted-packages: "*"
      interceptor-classes: "com.nextuple.common.interceptor.KafkaConsumerContextInterceptor"
      enable-auto-commit: true
      auto-offset-reset: latest
  sql.init.platform: postgres

logging:
  level:
    com.nextuple: DEBUG
entity-listener:
  kafka:
    enabled: false
pe:
  ui:
    allowed-origin-url: "*"

jobs-framework:
  feed-metrics-consumer:
    topic-name: INTERNAL.DEV.PE_JOB_FPM_METRICS_LOCAL, INTERNAL.DEV.PE_JOB_RECORD_FPM_METRICS_LOCAL, INTERNAL.DEV.PE_NEIP_FPM_METRICS_LOCAL
    group-id: pe-fpm-metrics-local
  job-completion-consumer:
    topic-name: job-completion-local
    group-id: jobs-completion-consumer-async-dev
  kafka-publish:
    topic-name: jobs-task-local
  result-publish:
    topic-name: jobs-result-local
  result-consumer:
    topic-name: jobs-result-local
    group-id: jobs-result-consumer-async-local
  record-consumer:
    topic-names: jobs-task-local
    group-id: jobs-task-consumer-async-local

pe-public-webhook:
  iv-feed:
    topic: INTERNAL.DEV_ATP
  item-feed:
    topic: ITEM_MASTER_INTEGRATION
  pe-response:
    topics: INTERNAL.DEV.CART_EDD
    group-id: pe-response-consumer-async-local
  webhook:
    - tenantId: NEXTUPLE_GR
      moduleName: PROMISING
      webhookName: PROMISING_INTERMEDIATE_EVENT
      webhookDetail:
        endpoint: "https://dc5647e2-a0d6-436b-bfba-6097594abe60.mock.pstmn.io"
        method: POST
        headers:
          contentType: "application/json"
          x-api-key: "PMAK-649a7ee4b2aa120030dfba82-4fe9121cae4c8059978d6e49f996cbefeb"
          #          Dummy API Key
    - tenantId: XYZINC
      moduleName: PROMISING
      webhookName: PROMISING_INTERMEDIATE_EVENT
      webhookDetail:
        endpoint: "https://dc5647e2-a0d6-436b-bfba-6097594abe60.mock.pstmn.io"
        method: POST
        headers:
          contentType: "application/json"
          x-api-key: "PMAK-649a7ee4b2aa120030dfba82-4fe9121cae4c8059978d6e49f996cbefeb"
          #          Dummy API Keydataupload:
dataupload:
  base-path: "https://pedataupload.blob.core.windows.net"
  maxsize-in-kilobytes: 10240
  max-rows: 1000
  bucket-name: "dataupload"
  type: BLOB
  signed-url-expiry-minutes: 30

master-data:
  node:
    topic-names: INTERNAL.DEV.PE.NODE_INTEGRATION
    group-id: node-master-dev
    dlt-topic: INTERNAL.DEV.PE.NODE_INTEGRATION.DLT
  node-carrier:
    topic-names: INTERNAL.DEV.PE.NODE_CARRIER_INTEGRATION
    group-id: node-carrier-master-dev
    dlt-topic: INTERNAL.DEV.PE.NODE_CARRIER_INTEGRATION.DLT
  carrier:
    topic-names: INTERNAL.DEV.PE.CARRIER_INTEGRATION
    group-id: carrier-master-dev
    dlt-topic: INTERNAL.DEV.PE.CARRIER_INTEGRATION.DLT
  processing-lead-time:
    topic-names: INTERNAL.DEV.PE.PROCESSING_LEAD_TIME_INTEGRATION
    group-id: processing-lead-time-master-dev
    dlt-topic: INTERNAL.DEV.PE.PROCESSING_LEAD_TIME_INTEGRATION.DLT
  calendar:
    topic-names: INTERNAL.DEV.PE.CALENDAR_INTEGRATION
    group-id: calendar-master-dev
    dlt-topic: INTERNAL.DEV.PE.CALENDAR_INTEGRATION.DLT
  node-calendar:
    topic-names: INTERNAL.DEV.PE.NODE_CALENDAR_INTEGRATION
    group-id: node-calendar-master-dev
    dlt-topic: INTERNAL.DEV.PE.NODE_CALENDAR_INTEGRATION.DLT
  carrier-service-calendar:
    topic-names: INTERNAL.DEV.PE.CARRIER_SERVICE_CALENDAR_INTEGRATION
    group-id: carrier-service-calendar-master-dev
    dlt-topic: INTERNAL.DEV.PE.CARRIER_SERVICE_CALENDAR_INTEGRATION.DLT
  pickup-calendar:
    topic-names: INTERNAL.DEV.PE.PICKUP_CALENDAR_INTEGRATION
    group-id: pickup-calendar-master-dev
    dlt-topic: INTERNAL.DEV.PE.PICKUP_CALENDAR_INTEGRATION.DLT
  node-service-option-buffer:
    topic-names: INTERNAL.DEV.PE.NODE_SERVICE_OPTION_BUFFER_INTEGRATION
    group-id: node-service-option-buffer-master-dev
    dlt-topic: INTERNAL.DEV.PE.NODE_SERVICE_OPTION_BUFFER_INTEGRATION.DLT
  transit:
    topic-names: INTERNAL.DEV.PE.TRANSIT_INTEGRATION
    group-id: transit-master-dev
    dlt-topic: INTERNAL.DEV.PE.TRANSIT_INTEGRATION
  transit-buffer:
    topic-names: INTERNAL.DEV.PE.TRANSIT_BUFFER_INTEGRATION
    group-id: transit-buffer-master-dev
    dlt-topic: INTERNAL.DEV.PE.TRANSIT_BUFFER_INTEGRATION.DLT
  item:
    dlt-topic: ITEM_MASTER_INTEGRATION.DLT
next-cache:
  caches:
    -
      cacheName: task-info
      ttlSeconds: 14400
      maxLimit: 50
  refresh-cache:
    topic: INTERNAL.DEV.PE.REFRESH_CACHE_INV
  cacheManager: caffeine
platform:
  tasks:
    enabled: false
  tasks-scheduler:
    enabled: true
    milliseconds: 5000
  authFilter:
    enabled: false
neo-platform:
  auth-injector:
    token-strategy: generate
    filter:
      enabled: true
    client-uri-mappings:
      my-client: /**
  auth-validator:
    application-name: pe-masterdata
    header:
      tenant-id: x-tenant-id
    issuer-uri: https://keycloak-nonprod.nextuple.com/realms/noms-dev
    authz-config:
      config-path: "http://plt-authz-config-uservice:8080/api/configurations/groups/application-group/scope-id/pe-masterdata"
      refresh-interval-mins: 30
      role:
        json-paths: \$.resource_access.tenantclient-nextuple.roles,\$.resource_access.tenantclient-kohls.roles,\$.resource_access.tenantclient-xyzinc.roles,\$.resource_access.tenantclient-abcinc.roles,\$.resource_access.tenantclient-neednow.roles,\$.resource_access.tenantclient-ctppt.roles,\$.resource_access.applicationclient-pe-masterdata-uservice.roles
kafka:
  input:
    taskTopics: INTERNAL.DEV.PE.RETRY_TOPIC_INV
    taskGroupId: pe-retry