
jobs-framework:
  feed-metrics-consumer:
    topic-name: INTERNAL.DEVPE.PE_JOB_FPM_METRICS, INTERNAL.DEVPE.PE_JOB_RECORD_FPM_METRICS, INTERNAL.DEVPE.PE_NEIP_FPM_METRICS
    group-id: pe-fpm-metrics-devpe
  job-completion-consumer:
    topic-name: INTERNAL.DEVPE.PE.JOB_COMPLETION
    group-id: jobs-completion-consumer-async-devpe
  kafka-publish:
    topic-name: INTERNAL.DEVPE.PE.JOB_TASK
  result-publish:
    topic-name: INTERNAL.DEVPE.PE.JOB_RESULT
  result-consumer:
    topic-name: INTERNAL.DEVPE.PE.JOB_RESULT
    group-id: jobs-result-consumer-async
  record-consumer:
    topic-name: INTERNAL.DEVPE.PE.JOB_TASK
    group-id: jobs-task-consumer-async

master-data:
  node:
    topic-name: INTERNAL.DEVPE.PE.NODE_INTEGRATION
    group-id: node-master-devpe
  node-carrier:
    topic-name: INTERNAL.DEVPE.PE.NODE_CARRIER_INTEGRATION
    group-id: node-carrier-master-devpe
  carrier:
    topic-name: INTERNAL.DEVPE.PE.CARRIER_INTEGRATION
    group-id: carrier-master-devpe
  processing-lead-time:
    topic-name: INTERNAL.DEVPE.PE.PROCESSING_LEAD_TIME_INTEGRATION
    group-id: processing-lead-time-master-devpe
  calendar:
    topic-name: INTERNAL.DEVPE.PE.CALENDAR_INTEGRATION
    group-id: calendar-master-devpe
  node-calendar:
    topic-name: INTERNAL.DEVPE.PE.NODE_CALENDAR_INTEGRATION
    group-id: node-calendar-master-devpe
  carrier-service-calendar:
    topic-name: INTERNAL.DEVPE.PE.CARRIER_SERVICE_CALENDAR_INTEGRATION
    group-id: carrier-service-calendar-master-devpe
  pickup-calendar:
    topic-name: INTERNAL.DEVPE.PE.PICKUP_CALENDAR_INTEGRATION
    group-id: pickup-calendar-master-devpe
  node-service-option-buffer:
    topic-name: INTERNAL.DEVPE.PE.NODE_SERVICE_OPTION_BUFFER_INTEGRATION
    group-id: node-service-option-buffer-master-devpe
  transit:
    topic-name: INTERNAL.DEVPE.PE.TRANSIT_INTEGRATION
    group-id: transit-master-devpe
  transit-buffer:
    topic-name: INTERNAL.DEVPE.PE.TRANSIT_BUFFER_INTEGRATION
    group-id: transit-buffer-master-devpe

next-cache:
  caches:
    -
      cacheName: task-info
      ttlSeconds: 14400
      maxLimit: 50
  refresh-cache:
    topic: INTERNAL.DEVPE.PE.REFRESH_CACHE_INV
  cacheManager: caffeine
platform:
  tasks:
    enabled: true
  tasks-scheduler:
    enabled: true
    milliseconds: 5000
  authFilter:
    enabled: false
kafka:
  input:
    taskTopics: INTERNAL.DEVPE.PE.RETRY_TOPIC_INV
    taskGroupId: pe-retry