spring:
  application:
    name: "pe-node"
    version: 2.6.0
    title: "Node Service"
    description: "Promising and sourcing engine node service"
    properties:
      group: promising-and-sourcing
      customerFacing: false
  main:
    allow-bean-definition-overriding: true
server:
  port: 8080
  tomcat:
    max-connections: 500
    threads:
      min-spare: 50
      max: 200

logging:
  level:
    org.springframework: WARN
    root: WARN
    com.nextuple: INFO
entity-listener:
  kafka:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
    metrics:
      enabled: true
    loggers:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
        persistence: true
        cache: true
#pe:
#  ui:
#    allowed-origin-url: \${PE_UI_URL}

pagination:
  pageNo: 1
  pageSize: 15
  sortBy: nodeId
  sortOrder: ASC
feign:
  okhttp:
    enabled: true
node:
  type: "STORE,FC,MFC,DROPSHIP VENDOR"
auth:
  filterEnabled: false
carrier:
  service:
    options: "SDND,STANDARD,EXPRESS,NEXTDAY"

