spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer-retry-count: 1
    consumer:
      enable-auto-commit: true
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.nextuple.item.consumer.serializer.ItemDeserializer
      topics:
        item_master:
          name: ITEM_MASTER_INTEGRATION
          group-id: item-master-local
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.nextuple.item.consumer.serializer.ItemSerializer

logging:
  level:
    com.nextuple: INFO
entity-listener:
  kafka:
    enabled: false
pe:
  ui:
    allowed-origin-url: "*"

dataupload:
  base-path: "https://pedataupload.blob.core.windows.net"
  bucket-name: "dataupload"
  type: BLOB
  signed-url-expiry-minutes: 30

jobs-framework:
  job-completion-consumer:
    topic-name: INTERNAL.DEV.PE.JOB_COMPLETION
    group-id: jobs-completion-consumer-async-dev