spring:
  application:
    dependencies:
      item: "http://localhost:8080/"
      node-carrier: "http://localhost:8080/"
      carrier: "http://localhost:8080/"
      transit: "http://localhost:8080/"
      data-upload: "http://localhost:8080/"
      node: "http://localhost:8080/"
      promise-sourcing-rule: "http://localhost:8080/"
      calendar: "http://localhost:8080/"
      postal-code-timezone: "http://localhost:8080/"
      weightage-configuration: "http://localhost:8080/"
      userexit: "http://localhost:8080/"
      configuration: "http://localhost:8080/"
      fpm-service: "http://localhost:8080/"
    name: "pe-masterdata-uservice"
    version: 2.6.0
    title: "Master Data Service"
    description: "Promising engine master data services"
    properties:
      group: promising-and-sourcing
      customerFacing: false
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        generate_statistics: true
server:
  port: 8080
  max-http-request-header-size: 20971520
  tomcat:
    max-connections: 500
    threads:
      min-spare: 50
      max: 200

logging:
  level:
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    com.zaxxer.hikari: WARN
    reactor.netty: WARN
    org.springframework: WARN
    root: WARN
    com.nextuple: INFO

entity-listener:
  kafka:
    enabled: true

constants:
  default-number-of-days-in-future: 45

pagination:
  pageNo: 1
  pageSize: 15

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
    metrics:
      enabled: true
    loggers:
      enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
        persistence: true
        cache: true
  prometheus.metrics.export.enabled: true
#pe:
#  ui:
#    allowed-origin-url: \${PE_UI_URL}
feign:
  okhttp:
    enabled: true
auth:
  filterEnabled: false

promise:
  service:
    options: "SDND,STANDARD,EXPRESS,NEXTDAY,BOPA,PRIME"

availability:
  keys: LINE,ORDER

base-api-url: '/promising-engine/pe-promise-sourcing-rule'

node-carrier-service-page-properties:
  sortBy: nodeId
  sortOrder: ASC
transit-time-buffer-page-properties:
  sortBy: carrierServiceId
  sortOrder: DESC

retry-properties:
  count: 5

page-properties:
  pageNo: 1
  pageSize: 15
  sortBy: created_date
  sortOrder: ASC

fpm-page-properties:
  pageNo: 1
  pageSize: 15
  sortBy: processing_started_at
  sortOrder: ASC

holidaycutoff-page-properties:
  sortBy: ruleName

scheduled-processor:
  timeRangeInHours: 24
  fixed-rate:
    minutes: 1
download-page-size:
  node-carrier-service-options: 200
  node: 200
  custom-region: 200
edd-computation:
  lines: 30
  orders: 10
csv-utility-api:
  csv-download:
    records-per-page: 200
    max-no-of-pages: 5
    max-no-of-failed-transit-entries: 1000
    max-no-of-carrier-services-for-download: 100
#item:
#  listenerContainerFactory: ItemDeserializerConsumer
platform:
  groupIdPrefix: pe-retry
holiday-cutoff:
  days: 0.0
  days-type: BUSINESS_DAYS

jobs-framework:
  consumer:
    enabled: true

neip:
  job-types: itembuffer,customregion
  headers:
    itembuffer: "RecordNo,action,orgId,itemId,uom,bufferHours,bufferStartDate,bufferEndDate,Error Message"
    customregion: "RecordNo,action,orgId,regionId,customRegionName,customRegionDescription,geozones,Error Message"
kafka-topic-flags:
  item-master:
    enabled: true
  master_data_update_event:
    enabled: true
  jobs-framework:
    feed-metrics-consumer:
      enabled: true
    job-completion-consumer:
      enabled: true
    kafka-publish:
      enabled: true
    result-publish:
      enabled: true
    result-consumer:
      enabled: true
    record-consumer:
      enabled: true
  pe-public-webhook:
    iv-feed:
      enabled: true
    item-feed:
      enabled: true
    pe-response:
      enabled: true
  master-data:
    node:
      enabled: false
    node-carrier:
      enabled: false
    carrier:
      enabled: false
    processing-lead-time:
      enabled: false
    calendar:
      enabled: false
    node-calendar:
      enabled: false
    carrier-service-calendar:
      enabled: false
    pickup-calendar:
      enabled: false
    node-service-option-buffer:
      enabled: false
    transit:
      enabled: false
    transit-buffer:
      enabled: false
  refresh-cache:
    enabled: false
  input:
    taskTopics:
      enabled: false
keycloak:
  realm: "NOMS"
  application-client: "applicationclient-pe_masterdata_uservice"
  enforcement-mode: "ENFORCING"
  http-method-as-scope: true