server:
  health-check-endpoint: "/actuator/health"
  environments:
    dev:
      replicas: 1
      resources:
        min:
          memory: "512Mi"
          cpu: "100m"
        max:
          memory: "512Mi"
          cpu: "2000m"
    qa:
      replicas: 1
      resources:
        min:
          memory: "512Mi"
          cpu: "100m"
        max:
          memory: "512Mi"
          cpu: "2000m"
    stage:
      replicas: 3
      resources:
        min:
          memory: "512Mi"
          cpu: "256m"
        max:
          memory: "512Mi"
          cpu: "256m"
    perf:
      java-opts: "-Xms768m -Xmx768m"
      replicas: 3
      resources:
        min:
          memory: "1024Mi"
          cpu: "500m"
        max:
          memory: "1024Mi"
          cpu: "500m"
    hotfix:
      replicas: 1
      resources:
        min:
          memory: "512Mi"
          cpu: "100m"
        max:
          memory: "512Mi"
          cpu: "2000m"
    prod:
      java-opts: "-Xms768m -Xmx768m"
      replicas: 3
      resources:
        min:
          memory: "1024Mi"
          cpu: "500m"
        max:
          memory: "1024Mi"
          cpu: "500m"
