server:
  health-check-endpoint: "/actuator/health"
  environments:
    dev:
      replicas: 1
      resources:
        min:
          memory: "512Mi"
          cpu: "100m"
        max:
          memory: "512Mi"
          cpu: "2000m"
    qa:
      replicas: 1
      resources:
        min:
          memory: "512Mi"
          cpu: "100m"
        max:
          memory: "512Mi"
          cpu: "2000m"
    stage:
      nlb: "no"
      replicas: 1
      resources:
        min:
          memory: "512Mi"
          cpu: "256m"
        max:
          memory: "512Mi"
          cpu: "256m"
    perf:
      java-opts: "-Xms1536m -Xmx1536m"
      replicas: 3
      resources:
        min:
          memory: "2048Mi"
          cpu: "1000m"
        max:
          memory: "2048Mi"
          cpu: "2000m"
    hotfix:
      nlb: "no"
      replicas: 1
      resources:
        min:
          memory: "512Mi"
          cpu: "100m"
        max:
          memory: "512Mi"
          cpu: "2000m"
    prod:
      java-opts: "-Xms1536m -Xmx1536m"
      replicas: 3
      resources:
        min:
          memory: "2048Mi"
          cpu: "1000m"
        max:
          memory: "2048Mi"
          cpu: "2000m"
