spring:
  application:
    dependencies:
      calendar: "http://localhost:8080/"
      node-carrier: "http://localhost:8084/"
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

logging:
  level:
    com.hbc: INFO
entity-listener:
  kafka:
    enabled: false
pe:
  ui:
    allowed-origin-url: "*"