spring:
  application:
    name: "pe-transit-uservice"
    version: ${version}
    title: "Transit Service"
    description: "Promising engine transit service"
    properties:
      group: promising-and-sourcing
      customerFacing: false
  main:
    allow-bean-definition-overriding: true

  kafka:
    consumer:
      enable-auto-commit: true
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        interceptor.classes: "com.nextuple.common.interceptor.KafkaConsumerContextInterceptor"
        max.poll.records: 10

  jpa:
    properties:
      hibernate:
        generate_statistics: true
server:
  port: 8080
  tomcat:
    max-connections: 500
    threads:
      min-spare: 50
      max: 200

logging:
  level:
    org.springframework: WARN
    org.apache.kafka: WARN
    org.springframework.kafka: WARN
    com.zaxxer.hikari: WARN
    reactor.netty: WARN
    root: WARN
    com.nextuple: INFO
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: false
    metrics:
      enabled: true
    loggers:
      enabled: true
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
        persistence: true
        cache: true

entity-listener:
  kafka:
    enabled: true
#pe:
#  ui:
#    allowed-origin-url: \${PE_UI_URL}
feign:
  okhttp:
    enabled: true
auth:
  filterEnabled: false
