spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://postgresql00-nonprod-wu2.nextuple.net:5432/pe_qa
    username: \${COMMON-PE-POSTGRES-USER}
    password: \${COMMON-PE-POSTGRES-PASSWORD}
  kafka:
    bootstrap-servers: kbrk-nonprod.nextuple.net:9092
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: \${COMMON-KAFKA-CONFIG}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      topics:
        master_data_update_event: INTERNAL.QA.MASTER_DATA_UPDATE_EVENTS
      properties:
        acks: 1
        retries: 5
        retry.backoff.ms: 1000
        spring.json.trusted.packages: "*"
        interceptor.classes: "com.nextuple.common.interceptor.KafkaProducerContextInterceptor"
  sql.init.platform: postgres

logging:
  level:
    com.nextuple: INFO

master-data:
  node-carrier:
    topic-name: INTERNAL.QA.PE.NODE_CARRIER_INTEGRATION
    group-id: node-carrier-master-qa
  processing-lead-time:
    topic-name: INTERNAL.QA.PE.PROCESSING_LEAD_TIME_INTEGRATION
    group-id: processing-lead-time-master-qa
  node-service-option-buffer:
    topic-name: INTERNAL.QA.PE.NODE_SERVICE_OPTION_BUFFER_INTEGRATION
    group-id: node-service-option-buffer-master-qa