spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://promise-engine-postgres-production.cluster-cboxgnkbeo0q.us-east-1.rds.amazonaws.com/peconfig
    username: \${POSTGRES_USER}
    password: \${POSTGRES_PWD}
    hikari:
      connectionTimeout: 5000
  replica:
    datasource:
      platform: postgres
      url: jdbc:postgresql://promise-engine-postgres-production.cluster-ro-cboxgnkbeo0q.us-east-1.rds.amazonaws.com,promise-engine-postgres-production.cluster-cboxgnkbeo0q.us-east-1.rds.amazonaws.com/peconfig?readOnly=true
      username: \${POSTGRES_USER}
      password: \${POSTGRES_PWD}
      required: true
      hikari:
        readOnly: true
        connectionTimeout: 5000
  kafka:
    bootstrap-servers: "b-3.promisemksproduction.wo9ili.c19.kafka.us-east-1.amazonaws.com:9096,b-1.promisemksproduction.wo9ili.c19.kafka.us-east-1.amazonaws.com:9096,b-2.promisemksproduction.wo9ili.c19.kafka.us-east-1.amazonaws.com:9096"
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-512
      sasl.jaas.config: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"\${KAFKA_USER}\" password=\"\${KAFKA_PWD}\";"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      topics:
        master_data_update_event: INTERNAL.PROD.MASTER_DATA_UPDATE_EVENTS
      properties:
        acks: 1
        retries: 5
        retry.backoff.ms: 1000
        spring.json.trusted.packages: "*"

logging:
  level:
    root: WARN
    com.nextuple: INFO

master-data:
  node-carrier:
    topic-names: INTERNAL.PROD.PE.NODE_CARRIER_INTEGRATION
    group-id: node-carrier-master-prod
  processing-lead-time:
    topic-names: INTERNAL.PROD.PE.PROCESSING_LEAD_TIME_INTEGRATION
    group-id: processing-lead-time-master-prod
  node-service-option-buffer:
    topic-names: INTERNAL.PROD.PE.NODE_SERVICE_OPTION_BUFFER_INTEGRATION
    group-id: node-service-option-buffer-master-prod