server:
  health-check-endpoint: "/actuator/health"
  environments:
    dev:
      replicas: 1
      resources:
        min:
          memory: "512Mi"
          cpu: "256m"
        max:
          memory: "512Mi"
          cpu: "256m"
    qa:
      replicas: 1
      resources:
        min:
          memory: "512Mi"
          cpu: "256m"
        max:
          memory: "512Mi"
          cpu: "256m"
    stage:
      replicas: 1
      resources:
        min:
          memory: "512Mi"
          cpu: "256m"
        max:
          memory: "512Mi"
          cpu: "256m"
    perf:
      replicas: 3
      resources:
        min:
          memory: "512Mi"
          cpu: "256m"
        max:
          memory: "512Mi"
          cpu: "256m"
