spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://postgresql00-nonprod-wu2.nextuple.net:5432/pe
    username: \${COMMON-PE-POSTGRES-USER}
    password: \${COMMON-PE-POSTGRES-PASSWORD}
  kafka:
    bootstrap-servers: kbrk-nonprod.nextuple.net:9092
    properties:
      security.protocol: SASL_PLAINTEXT
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: \${COMMON-KAFKA-CONFIG}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      topics:
        master_data_update_event: INTERNAL.DEV.MASTER_DATA_UPDATE_EVENTS
      properties:
        acks: 1
        retries: 5
        retry.backoff.ms: 1000
        spring.json.trusted.packages: "*"
        interceptor.classes: "com.nextuple.common.interceptor.KafkaProducerContextInterceptor"
  sql.init.platform: postgres
logging:
  level:
    com.nextuple: INFO
master-data:
  node:
    topic-names: INTERNAL.DEV.PE.NODE_INTEGRATION
    group-id: node-master-dev