spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://promise-engine-postgres-dev.co9l0bkmgaei.us-east-1.rds.amazonaws.com/pe_qa
    username: \${POSTGRES_USER}
    password: \${POSTGRES_PWD}
  kafka:
    bootstrap-servers: "b-3.promisemksdevelopment.kmb9h1.c25.kafka.us-east-1.amazonaws.com:9096,b-2.promisemksdevelopment.kmb9h1.c25.kafka.us-east-1.amazonaws.com:9096,b-1.promisemksdevelopment.kmb9h1.c25.kafka.us-east-1.amazonaws.com:9096"
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-512
      sasl.jaas.config: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"\${KAFKA_USER}\" password=\"\${KAFKA_PWD}\";"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      topics:
        master_data_update_event: INTERNAL.QA.MASTER_DATA_UPDATE_EVENTS
      properties:
        acks: all
        retries: 5
        retry.backoff.ms: 1000
        spring.json.trusted.packages: "*"

logging:
  level:
    com.nextuple: DEBUG
auth:
  issuer: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_FAqWuc7OP