spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://promise-engine-postgres-prod.cluster-cboxgnkbeo0q.us-east-1.rds.amazonaws.com/pe
    username: \${POSTGRES_USER}
    password: \${POSTGRES_PWD}
  replica:
    datasource:
      platform: postgres
      url: jdbc:postgresql://promise-engine-postgres-prod.cluster-ro-cboxgnkbeo0q.us-east-1.rds.amazonaws.com,promise-engine-postgres-prod.cluster-cboxgnkbeo0q.us-east-1.rds.amazonaws.com/pe?readOnly=true
      username: \${POSTGRES_USER}
      password: \${POSTGRES_PWD}
      required: true
      hikari:
        readOnly: true
  kafka:
    bootstrap-servers: "b-1.promiseenginekafkapro.o79lf2.c23.kafka.us-east-1.amazonaws.com:9096,b-2.promiseenginekafkapro.o79lf2.c23.kafka.us-east-1.amazonaws.com:9096,b-3.promiseenginekafkapro.o79lf2.c23.kafka.us-east-1.amazonaws.com:9096"
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-512
      sasl.jaas.config: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"\${KAFKA_USER}\" password=\"\${KAFKA_PWD}\";"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: "*"
        acks: 1
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"

logging:
  level:
    root: WARN
    com.hbc: INFO
auth:
  issuer: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_phMvZ9Tci

dataupload:
  base-path: "/s3-bucket/"
  maxsize-in-kilobytes: 10240
  max-rows: 10000

jobs-framework:
  kafka-publish:
    topic-name: INTERNAL.PROD.JOBS.TASK
  result-publish:
    topic-name: INTERNAL.PROD.JOBS.RESULT
  result-consumer:
    topic-name: INTERNAL.PROD.JOBS.RESULT
    group-id: jobs-result-consumer-async-prod
  record-consumer:
    topic-name: INTERNAL.PROD.JOBS.TASK
    group-id: jobs-task-consumer-async-prod