spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://promise-engine-postgres-perf.cluster-co9l0bkmgaei.us-east-1.rds.amazonaws.com/pe
    username: \${POSTGRES_USER}
    password: \${POSTGRES_PWD}
  kafka:
    bootstrap-servers: "b-1.devkafkacluster.jhsucn.c23.kafka.us-east-1.amazonaws.com:9096,b-2.devkafkacluster.jhsucn.c23.kafka.us-east-1.amazonaws.com:9096,b-2.devkafkacluster.jhsucn.c23.kafka.us-east-1.amazonaws.com:9096"
    consumer-retry-count: 3
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-512
      sasl.jaas.config: "org.apache.kafka.common.security.scram.ScramLoginModule required username=\"\${KAFKA_USER}\" password=\"\${KAFKA_PWD}\";"
    consumer:
      enable-auto-commit: true
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.hbc.item.consumer.serializer.ItemDeserializer
      topics:
        item_master:
          name: dev.items.promise.bay.v1
          group-id: item-master-dev
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.hbc.item.consumer.serializer.ItemSerializer

logging:
  level:
    com.hbc: DEBUG