spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://promise-engine-postgres-prod.cluster-cboxgnkbeo0q.us-east-1.rds.amazonaws.com/pe
    username: \${POSTGRES_USER}
    password: \${POSTGRES_PWD}
  replica:
    datasource:
      platform: postgres
      url: jdbc:postgresql://promise-engine-postgres-prod.cluster-ro-cboxgnkbeo0q.us-east-1.rds.amazonaws.com/pe?readOnly=true
      username: \${POSTGRES_USER}
      password: \${POSTGRES_PWD}
      required: true
      hikari:
        readOnly: true
  kafka:
    bootstrap-servers: "loyalty-prod-bootstrap.integration.awshbc.io:9094"
    consumer-retry-count: 1
    consumer:
      enable-auto-commit: true
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.hbc.item.consumer.serializer.ItemDeserializer
      topics:
        item_master:
          name: items.promise.bay.v1
          group-id: item-master-prod
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.hbc.item.consumer.serializer.ItemSerializer

logging:
  level:
    root: WARN
    com.hbc: INFO
auth:
  issuer: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_phMvZ9Tci