create table if not exists attribute_value
(
    id                 bigint generated by default as identity
    primary key,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    created_by         varchar(255),
    updated_by         varchar(255),
    name_id            bigint,
    value              varchar(255)
    );


create table if not exists calendars
(
    calendar_id          varchar(255) not null,
    org_id               varchar(255) not null,
    created_date         timestamp(6),
    last_modified_date   timestamp(6),
    created_by           varchar(255),
    updated_by           varchar(255),
    description          varchar(255),
    exception_days       jsonb,
    is_friday_working    boolean,
    is_monday_working    boolean,
    is_saturday_working  boolean,
    is_sunday_working    boolean,
    is_thursday_working  boolean,
    is_tuesday_working   boolean,
    is_wednesday_working boolean,
    primary key (calendar_id, org_id)
    );



create table if not exists carrier_service
(
    carrier_id         varchar(255) not null,
    carrier_service_id varchar(255) not null,
    org_id             varchar(255) not null,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    created_by         varchar(255),
    updated_by         varchar(255),
    carrier_name       varchar(255),
    service_name       varchar(255),
    service_options    varchar(255),
    primary key (carrier_id, carrier_service_id, org_id)
    );



create index if not exists orgid_carrierserviceid
    on carrier_service (org_id, carrier_service_id);

create table if not exists carrier_service_calendars
(
    calendar_id        varchar(255) not null,
    carrier_service_id varchar(255) not null,
    effective_date     varchar(255) not null,
    org_id             varchar(255) not null,
    shipping_stage     varchar(255) not null,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    created_by         varchar(255),
    updated_by         varchar(255),
    description        varchar(255),
    primary key (calendar_id, carrier_service_id, effective_date, org_id, shipping_stage)
    );



create table if not exists config_metadata
(
    id                   bigint generated by default as identity
    primary key,
    created_date         timestamp(6),
    last_modified_date   timestamp(6),
    created_by           varchar(255),
    updated_by           varchar(255),
    app_name             varchar(255),
    config_key           varchar(255),
    default_config_value varchar(500)
    );



create table if not exists cost_attribute_details
(
    id                    bigint generated by default as identity
    primary key,
    created_date          timestamp(6),
    last_modified_date    timestamp(6),
    created_by            varchar(255),
    updated_by            varchar(255),
    attribute_description varchar(255),
    attribute_name        varchar(255),
    display_name          varchar(255),
    is_published          boolean,
    lookup_context        smallint
    constraint cost_attribute_details_lookup_context_check
    check ((lookup_context >= 0) AND (lookup_context <= 1)),
    path                  varchar(255)
    );



create index if not exists cost_attribute_id_attribute_name
    on cost_attribute_details (id, attribute_name);

create table if not exists cost_attribute_mapping
(
    id                 bigint generated by default as identity
    primary key,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    created_by         varchar(255),
    updated_by         varchar(255),
    attribute_name     varchar(255),
    canonical_name     varchar(255),
    display_name       varchar(255),
    org_id             varchar(255)
    );



create index if not exists cost_attribute_mapping_id_orgid
    on cost_attribute_mapping (id, org_id);

create table if not exists cost_factor
(
    id                            bigint generated by default as identity
    primary key,
    created_date                  timestamp(6),
    last_modified_date            timestamp(6),
    created_by                    varchar(255),
    updated_by                    varchar(255),
    cost_factor                   varchar(255),
    cost_factor_type              smallint
    constraint cost_factor_cost_factor_type_check
    check ((cost_factor_type >= 0) AND (cost_factor_type <= 1)),
    data_type                     smallint
    constraint cost_factor_data_type_check
    check ((data_type >= 0) AND (data_type <= 1)),
    default_value                 varchar(255),
    display_name                  varchar(255),
    formula                       varchar(255),
    is_bucketed                   boolean,
    is_rate_card_look_up_required boolean,
    level_applied                 smallint
    constraint cost_factor_level_applied_check
    check ((level_applied >= 0) AND (level_applied <= 3)),
    library                       smallint
    constraint cost_factor_library_check
    check ((library >= 0) AND (library <= 1)),
    org_id                        varchar(255),
    uom                           varchar(255),
    values                        text
    );



create index if not exists cost_factor_id_orgid
    on cost_factor (id, org_id);

create table if not exists cost_factor_audit_log
(
    id               bigint generated by default as identity
    primary key,
    cost_factor      varchar(255),
    cost_factor_type smallint
    constraint cost_factor_audit_log_cost_factor_type_check
    check ((cost_factor_type >= 0) AND (cost_factor_type <= 1)),
    data_type        smallint
    constraint cost_factor_audit_log_data_type_check
    check ((data_type >= 0) AND (data_type <= 1)),
    default_value    varchar(255),
    display_name     varchar(255),
    formula          varchar(255),
    is_bucketed      boolean,
    level_applied    smallint
    constraint cost_factor_audit_log_level_applied_check
    check ((level_applied >= 0) AND (level_applied <= 3)),
    library          smallint
    constraint cost_factor_audit_log_library_check
    check ((library >= 0) AND (library <= 1)),
    org_id           varchar(255),
    timestamp        timestamp(6),
    uom              varchar(255),
    values           text
    );



create index if not exists cost_factor_audit_log_id_orgid
    on cost_factor_audit_log (id, org_id);

create table if not exists cost_factor_bucket_type
(
    id          bigint generated by default as identity
    primary key,
    bucket_type smallint
    constraint cost_factor_bucket_type_bucket_type_check
    check ((bucket_type >= 0) AND (bucket_type <= 1)),
    cost_factor varchar(255),
    org_id      varchar(255)
    );



create index if not exists cost_factor_bucket_type_orgid_costfactor
    on cost_factor_bucket_type (org_id, cost_factor);

create table if not exists cost_factor_contiguous_buckets
(
    id                     bigint generated by default as identity
    primary key,
    cost_factor            varchar(255),
    from_value             double precision,
    is_min_value_inclusive boolean,
    is_max_value_inclusive boolean,
    notation               varchar(255),
    notation_display_name  varchar(255),
    org_id                 varchar(255),
    max_value              double precision
    );



create index if not exists cost_factor_contiguous_buckets_orgid_costfactor_notation
    on cost_factor_contiguous_buckets (org_id, cost_factor, notation);

create table if not exists cost_factor_discrete_bucket
(
    id                    bigint generated by default as identity
    primary key,
    cost_factor           varchar(255),
    notation              varchar(255),
    notation_display_name varchar(255),
    org_id                varchar(255),
    value_list            varchar(255)
    );



create index if not exists cost_factor_discrete_bucket_orgid_costfactor_notation
    on cost_factor_discrete_bucket (org_id, cost_factor, notation);

create table if not exists cost_itinerary_and_factors
(
    id               bigint generated by default as identity
    primary key,
    cost_factors     varchar(255),
    cost_itinerary   varchar(255),
    is_active        boolean,
    itinerary_status smallint
    constraint cost_itinerary_and_factors_itinerary_status_check
    check ((itinerary_status >= 0) AND (itinerary_status <= 1)),
    level_applied    smallint
    constraint cost_itinerary_and_factors_level_applied_check
    check ((level_applied >= 0) AND (level_applied <= 3)),
    org_id           varchar(255)
    );



create index if not exists cost_itinerary_and_factors_id_orgid
    on cost_itinerary_and_factors (id, org_id);

create table if not exists cost_value
(
    id                          bigint generated by default as identity
    primary key,
    created_date                timestamp(6),
    last_modified_date          timestamp(6),
    created_by                  varchar(255),
    updated_by                  varchar(255),
    cost_factor_combination_key varchar(255),
    cost_itinerary              varchar(255),
    cost_value                  double precision,
    org_id                      varchar(255),
    prev_slab_value             varchar(255)
    );



create index if not exists cost_value_id_orgid
    on cost_value (id, org_id);

create table if not exists custom_region
(
    id                 varchar(255) not null,
    org_id             varchar(255) not null,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    created_by         varchar(255),
    updated_by         varchar(255),
    codes              varchar(255)[],
    description        varchar(255),
    name               varchar(255),
    primary key (id, org_id)
    );



create index if not exists customregionid_orgid
    on custom_region (id, org_id);

create table if not exists feed_records
(
    id                     varchar(255) not null
    primary key,
    correlation_id         varchar(255),
    created_by             varchar(255),
    deleted                boolean,
    document_version       integer      not null,
    error_message          varchar(255),
    exception              varchar(255),
    job_type               varchar(255),
    job_id                 varchar(255),
    job_references         bytea,
    org_id                 varchar(255),
    raw_request            varchar(10000),
    record_no              integer,
    request_body           varchar(10000),
    response_body          varchar(10000),
    response_body_present  boolean,
    response_time          bigint,
    service_correlation_id varchar(255),
    status                 varchar(255)
    constraint feed_records_status_check
    check ((status)::text = ANY ((ARRAY ['SUCCESS'::character varying, 'FAILURE'::character varying])::text[])),
    status_code            integer,
    updated_by             varchar(255),
    user_id                varchar(255)
    );



create index if not exists feed_jobid_key
    on feed_records (job_id);

create table if not exists feed_templates
(
    id                varchar(255) not null
    primary key,
    feed_content_type varchar(255),
    feed_type         varchar(255),
    org_id            varchar(255),
    schema            jsonb
    );



create index if not exists orgid_feed_type
    on feed_templates (org_id, feed_type);

create table if not exists feeds
(
    job_id                  varchar(255) not null
    primary key,
    audit_log               jsonb,
    error_message           varchar(255),
    failure_count           integer,
    feed_type               varchar(255),
    file_name               varchar(255),
    file_path               varchar(255),
    org_id                  varchar(255),
    processed_records       integer,
    processing_completed_at timestamp(6),
    processing_started_at   timestamp(6),
    remaining_records       integer,
    source_application_name varchar(255),
    status                  varchar(255)
    constraint feeds_status_check
    check ((status)::text = ANY
((ARRAY ['SUBMITTED'::character varying, 'PROCESSING'::character varying, 'PROCESSED'::character varying, 'FAILED'::character varying, 'RUNNING'::character varying, 'COMPLETED'::character varying])::text[])),
    storage_type            varchar(255),
    success_count           integer,
    total_records           integer,
    user_id                 varchar(255)
    );



create index if not exists feed_status
    on feeds (status);

create index if not exists feed_orgid_jobid
    on feeds (org_id, job_id);

create table if not exists file_metadata
(
    id                 bigint generated by default as identity
    primary key,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    created_by         varchar(255),
    updated_by         varchar(255),
    description        varchar(255),
    ext_reference_id   varchar(255),
    name               varchar(255),
    parent_file_id     bigint,
    path               varchar(255),
    size               varchar(255),
    storage_type       varchar(255),
    type               varchar(255)
    );



create table if not exists group_definition
(
    id                                bigint generated by default as identity
    primary key,
    created_date                      timestamp(6),
    last_modified_date                timestamp(6),
    created_by                        varchar(255),
    updated_by                        varchar(255),
    group_name                        varchar(255),
    optional_attributes_value         varchar(255),
    org_id                            varchar(255),
    req_attributes_value              varchar(255),
    sourcing_attributes_definition_id bigint
    );



create index if not exists orgid_sourcingattributesdefinitionid_index
    on group_definition (org_id, sourcing_attributes_definition_id);

create table if not exists holiday_cutoff
(
    holiday_cutoff_name               varchar(255) not null,
    holiday_cutoff_rule               varchar(255) not null,
    org_id                            varchar(255) not null,
    created_date                      timestamp(6),
    last_modified_date                timestamp(6),
    created_by                        varchar(255),
    updated_by                        varchar(255),
    delivery_cool_down_days           double precision,
    delivery_cool_down_days_type      varchar(255)
    constraint holiday_cutoff_delivery_cool_down_days_type_check
    check ((delivery_cool_down_days_type)::text = ANY
((ARRAY ['BUSINESS_DAYS'::character varying, 'CALENDAR_DAYS'::character varying])::text[])),
    holiday_cutoff_date               timestamp(6),
    holiday_cutoff_description        varchar(255),
    holiday_delivery_date             timestamp(6),
    pre_cutoff_days                   double precision,
    pre_cutoff_days_type              varchar(255)
    constraint holiday_cutoff_pre_cutoff_days_type_check
    check ((pre_cutoff_days_type)::text = ANY
((ARRAY ['BUSINESS_DAYS'::character varying, 'CALENDAR_DAYS'::character varying])::text[])),
    sourcing_attributes_definition_id bigint,
    start_date                        timestamp(6),
    status                            varchar(255)
    constraint holiday_cutoff_status_check
    check ((status)::text = ANY ((ARRAY ['ACTIVE'::character varying, 'INACTIVE'::character varying])::text[])),
    primary key (holiday_cutoff_name, holiday_cutoff_rule, org_id)
    );



create index if not exists orgid_sourcingattributesdefinitionid_holidaycutoffrule
    on holiday_cutoff (org_id, sourcing_attributes_definition_id, holiday_cutoff_rule);

create table if not exists item
(
    item_id                      varchar(255) not null,
    org_id                       varchar(255) not null,
    uom                          varchar(255) not null,
    created_date                 timestamp(6),
    last_modified_date           timestamp(6),
    created_by                   varchar(255),
    updated_by                   varchar(255),
    buying_cost                  integer,
    color                        varchar(255),
    cost                         varchar(255),
    department_name              varchar(255),
    department_number            varchar(255),
    dimension_uom                varchar(255),
    handling_type                varchar(255),
    height                       double precision,
    image_url                    varchar(255),
    inventory_node_types         jsonb,
    is_dsv_eligible              boolean,
    is_hazmat                    boolean,
    is_white_glove               boolean,
    item_banner                  varchar(255),
    item_source                  varchar(255),
    lead_time                    bigint,
    length                       double precision,
    parcel_shipment_eligible     boolean,
    pick_eligible                boolean,
    processing_time              double precision,
    product                      varchar(255),
    service_option_eligibilities jsonb,
    ship_alone                   boolean,
    ship_eligible                boolean,
    short_description            varchar(255),
    size                         varchar(255),
    valid_dropoff_duration       double precision,
    vendor_type                  varchar(255),
    volume                       double precision,
    volume_uom                   varchar(255),
    weight                       double precision,
    weight_uom                   varchar(255),
    width                        double precision,
    primary key (item_id, org_id, uom)
    );



create table if not exists item_buffers_data
(
    id                 bigint generated by default as identity
    primary key,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    created_by         varchar(255),
    updated_by         varchar(255),
    buffer_end_date    timestamp(6),
    buffer_hours       double precision,
    buffer_start_date  timestamp(6),
    item_id            varchar(255),
    org_id             varchar(255),
    uom                varchar(255)
    );



create index if not exists itemid_orgid_uom_bufferstartdate_bufferenddate_index
    on item_buffers_data (item_id, org_id, uom, buffer_start_date, buffer_end_date);

create table if not exists job_records
(
    id                     varchar(255) not null
    primary key,
    created_date           timestamp(6),
    last_modified_date     timestamp(6),
    correlation_id         varchar(255),
    created_by             varchar(255),
    deleted                boolean,
    document_version       integer      not null,
    error_message          varchar(255),
    exception              varchar(255),
    job_id                 varchar(255),
    job_references         bytea,
    job_type               varchar(255)
    constraint job_records_job_type_check
    check ((job_type)::text = ANY
((ARRAY ['UPLOAD_TRANSIT_TIMES'::character varying, 'UPLOAD_PROCESSING_LEAD_TIMES'::character varying, 'DELETE_TRANSIT_BUFFER'::character varying, 'TRANSIT_BUFFER_REQUEST'::character varying, 'UPLOAD_POSTAL_CODE_TIMEZONE'::character varying, 'UPLOAD_NODES'::character varying, 'UPLOAD_NODE_CARRIER'::character varying, 'UPLOAD_NODE_CALENDER'::character varying, 'UPLOAD_CARRIER_SERVICE'::character varying, 'UPLOAD_CARRIER_SERVICE_CALENDER'::character varying, 'UPLOAD_CALENDER'::character varying, 'UPLOAD_PICKUP_CALENDER'::character varying, 'UPLOAD_NODE_SERVICE_OPTION_BUFFER'::character varying, 'UPLOAD_CUSTOM_REGION'::character varying, 'UPLOAD_ZONES'::character varying, 'UPLOAD_COST_DEFINITION'::character varying, 'UPLOAD_FROM_NEIP'::character varying])::text[])),
    org_id                 varchar(255),
    record_no              integer,
    request_body           varchar(10000),
    response_body          varchar(10000),
    response_body_present  boolean,
    response_time          bigint,
    service_correlation_id varchar(255),
    status                 varchar(255)
    constraint job_records_status_check
    check ((status)::text = ANY ((ARRAY ['SUCCESS'::character varying, 'FAILURE'::character varying])::text[])),
    status_code            integer,
    updated_by             varchar(255),
    user_id                varchar(255)
    );



create index if not exists jobid_key
    on job_records (job_id);

create table if not exists jobs
(
    job_id                varchar(255) not null
    primary key,
    created_date          timestamp(6),
    last_modified_date    timestamp(6),
    audit_log             jsonb,
    error_message         varchar(255),
    failure_count         integer,
    file                  oid,
    file_metadata_id      bigint,
    file_name             varchar(255),
    job_type              varchar(255)
    constraint jobs_job_type_check
    check ((job_type)::text = ANY
((ARRAY ['UPLOAD_TRANSIT_TIMES'::character varying, 'UPLOAD_PROCESSING_LEAD_TIMES'::character varying, 'DELETE_TRANSIT_BUFFER'::character varying, 'TRANSIT_BUFFER_REQUEST'::character varying, 'UPLOAD_POSTAL_CODE_TIMEZONE'::character varying, 'UPLOAD_NODES'::character varying, 'UPLOAD_NODE_CARRIER'::character varying, 'UPLOAD_NODE_CALENDER'::character varying, 'UPLOAD_CARRIER_SERVICE'::character varying, 'UPLOAD_CARRIER_SERVICE_CALENDER'::character varying, 'UPLOAD_CALENDER'::character varying, 'UPLOAD_PICKUP_CALENDER'::character varying, 'UPLOAD_NODE_SERVICE_OPTION_BUFFER'::character varying, 'UPLOAD_CUSTOM_REGION'::character varying, 'UPLOAD_ZONES'::character varying, 'UPLOAD_COST_DEFINITION'::character varying, 'UPLOAD_FROM_NEIP'::character varying])::text[])),
    org_id                varchar(255),
    processed_records     integer,
    processing_started_at timestamp(6),
    remaining_records     integer,
    status                varchar(255)
    constraint jobs_status_check
    check ((status)::text = ANY
((ARRAY ['SUBMITTED'::character varying, 'PROCESSING'::character varying, 'PROCESSED'::character varying, 'FAILED'::character varying, 'RUNNING'::character varying, 'COMPLETED'::character varying])::text[])),
    success_count         integer,
    total_records         integer,
    user_id               varchar(255)
    );



create index if not exists status_key
    on jobs (status);

create index if not exists orgid_jobid
    on jobs (org_id, job_id);

create table if not exists named_optimization_strategy
(
    id                            bigint generated by default as identity
    primary key,
    created_date                  timestamp(6),
    last_modified_date            timestamp(6),
    created_by                    varchar(255),
    updated_by                    varchar(255),
    group_id                      varchar(255),
    optimization_strategy_details varchar(255),
    optimization_strategy_name    varchar(255),
    org_id                        varchar(255)
    );



create table if not exists node
(
    node_id                      varchar(255) not null,
    org_id                       varchar(255) not null,
    created_date                 timestamp(6),
    last_modified_date           timestamp(6),
    created_by                   varchar(255),
    updated_by                   varchar(255),
    bopis_eligible               boolean,
    city                         varchar(255),
    country                      varchar(255),
    is_active                    boolean,
    last_working_time            varchar(255),
    latitude                     varchar(255),
    longitude                    varchar(255),
    node_labour_tier             varchar(255),
    node_type                    varchar(255),
    service_option_eligibilities jsonb,
    ship_to_home                 boolean,
    start_working_time           varchar(255),
    state                        varchar(255),
    street                       varchar(255),
    timezone                     varchar(255),
    zip_code                     varchar(255),
    primary key (node_id, org_id)
    );



create table if not exists node_calendars
(
    calendar_id        varchar(255) not null,
    effective_date     varchar(255) not null,
    node_id            varchar(255) not null,
    org_id             varchar(255) not null,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    created_by         varchar(255),
    updated_by         varchar(255),
    description        varchar(255),
    primary key (calendar_id, effective_date, node_id, org_id)
    );



create table if not exists node_carrier
(
    carrier_service_id varchar(255) not null,
    node_id            varchar(255) not null,
    org_id             varchar(255) not null,
    service_option     varchar(255) not null,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    created_by         varchar(255),
    updated_by         varchar(255),
    buffer_end_date    timestamp(6),
    buffer_hours       double precision,
    buffer_start_date  timestamp(6),
    last_pickup_time   varchar(255),
    processing_time    double precision,
    primary key (carrier_service_id, node_id, org_id, service_option)
    );



create table if not exists node_carrier_selection
(
    destination_geozone varchar(255) not null,
    org_id              varchar(255) not null,
    service_option      varchar(255) not null,
    source_geozone      varchar(255) not null,
    created_date        timestamp(6),
    last_modified_date  timestamp(6),
    created_by          varchar(255),
    updated_by          varchar(255),
    priority            varchar(255),
    primary key (destination_geozone, org_id, service_option, source_geozone)
    );



create table if not exists node_carrier_service_calendars
(
    calendar_id        varchar(255) not null,
    carrier_service_id varchar(255) not null,
    effective_date     varchar(255) not null,
    node_id            varchar(255) not null,
    org_id             varchar(255) not null,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    created_by         varchar(255),
    updated_by         varchar(255),
    description        varchar(255),
    primary key (calendar_id, carrier_service_id, effective_date, node_id, org_id)
    );



create table if not exists node_carriers
(
    carrier_service_id varchar(255) not null,
    node_id            varchar(255) not null,
    org_id             varchar(255) not null,
    service_option     varchar(255) not null,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    created_by         varchar(255),
    updated_by         varchar(255),
    last_pickup_time   varchar(255),
    primary key (carrier_service_id, node_id, org_id, service_option)
    );



create table if not exists node_group
(
    id                     bigint generated by default as identity
    primary key,
    created_date           timestamp(6),
    last_modified_date     timestamp(6),
    created_by             varchar(255),
    updated_by             varchar(255),
    node_group_description varchar(255),
    node_group_name        varchar(255),
    org_id                 varchar(255)
    );



create table if not exists node_priority
(
    id                 bigint generated by default as identity
    primary key,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    created_by         varchar(255),
    updated_by         varchar(255),
    node_group_id      bigint,
    node_id            varchar(255),
    org_id             varchar(255),
    priority           integer
    );



create index if not exists orgid_nodegroupid
    on node_priority (org_id, node_group_id);

create table if not exists node_service_option
(
    node_id            varchar(255) not null,
    org_id             varchar(255) not null,
    service_option     varchar(255) not null,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    created_by         varchar(255),
    updated_by         varchar(255),
    processing_time    double precision,
    primary key (node_id, org_id, service_option)
    );



create table if not exists node_service_option_buffers
(
    id                 bigint generated by default as identity
    primary key,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    created_by         varchar(255),
    updated_by         varchar(255),
    buffer_end_date    timestamp(6),
    buffer_hours       double precision,
    buffer_start_date  timestamp(6),
    node_id            varchar(255),
    org_id             varchar(255),
    service_option     varchar(255)
    );



create index if not exists orgid_nodeid_serviceoption_index
    on node_service_option_buffers (org_id, node_id, service_option);

create table if not exists optimization_and_cost_types_mapping
(
    id                    bigint generated by default as identity
    primary key,
    cost_types            varchar(255),
    description           varchar(255),
    java_class_name       varchar(255),
    optimization_strategy varchar(255),
    org_id                varchar(255)
    );



create index if not exists optimization_and_cost_types_mapping_id_orgid
    on optimization_and_cost_types_mapping (id, org_id);

create table if not exists postal_code
(
    org_id             varchar(255) not null,
    zip_code           varchar(255) not null,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    created_by         varchar(255),
    updated_by         varchar(255),
    city               varchar(255),
    country            varchar(255),
    custom_region      varchar(255),
    latitude           varchar(255),
    longitude          varchar(255),
    state              varchar(255),
    timezone           varchar(255),
    zip_code_prefix    varchar(255),
    primary key (org_id, zip_code)
    );



create index if not exists orgid_zipcodeid
    on postal_code (org_id, zip_code);

create index if not exists orgid_zipcodeprefix
    on postal_code (org_id, zip_code_prefix);

create table if not exists postal_code_timezone
(
    org_id             varchar(255) not null,
    zip_code_prefix    varchar(255) not null,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    created_by         varchar(255),
    updated_by         varchar(255),
    city               varchar(255),
    country            varchar(255),
    latitude           varchar(255),
    longitude          varchar(255),
    state              varchar(255),
    time_zone          varchar(255),
    primary key (org_id, zip_code_prefix)
    );



create table if not exists preference_selector
(
    id                 bigint generated by default as identity
    primary key,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    created_by         varchar(255),
    updated_by         varchar(255),
    cost_type          varchar(255),
    org_id             varchar(255),
    selector_cf        varchar(255)
    );



create index if not exists preference_selector_id_orgid
    on preference_selector (id, org_id);

create table if not exists promise_sourcing_rule
(
    allocation_rule_id   varchar(255) not null,
    destination_geo_zone varchar(255) not null,
    org_id               varchar(255) not null,
    priority             integer      not null,
    service_option       varchar(255) not null,
    created_date         timestamp(6),
    last_modified_date   timestamp(6),
    created_by           varchar(255),
    updated_by           varchar(255),
    source_nodes         json,
    primary key (allocation_rule_id, destination_geo_zone, org_id, priority, service_option)
    );



create index if not exists orgid_serviceoption_destinationgeozone_allocationruleid
    on promise_sourcing_rule (org_id, service_option, destination_geo_zone, allocation_rule_id);

create table if not exists purge_config
(
    id                 bigint generated by default as identity
    primary key,
    archive_table_name varchar(255),
    batch_size         integer,
    criteria_query     varchar(255),
    delete_bean_class  varchar(255),
    mode               varchar(255),
    offset_days        integer,
    offset_field       varchar(255),
    page_size          integer,
    primary_key_field  varchar(255),
    purge_id           varchar(255),
    sleep_timeout      bigint,
    table_name         varchar(255),
    tenant             varchar(255),
    constraint ukmbxd3bntl97wqq59c4twbdvje
    unique (purge_id, tenant)
    );



create table if not exists rules_configuration
(
    module_name             varchar(255) not null
    constraint rules_configuration_module_name_check
    check ((module_name)::text = ANY
((ARRAY ['PROCESSING_TIME'::character varying, 'TRANSFER_SCHEDULE'::character varying])::text[])),
    org_id                  varchar(255) not null,
    rule                    varchar(255) not null,
    rule_name               varchar(255) not null,
    scope                   varchar(255) not null
    constraint rules_configuration_scope_check
    check ((scope)::text = ANY
((ARRAY ['SOURCING_RULE'::character varying, 'OPTIMIZATION'::character varying, 'HOLIDAY_CUTOFF'::character varying, 'ML_RULE'::character varying, 'ML_OVERRIDE_RULE'::character varying, 'TRANSFER_SCHEDULE_RULE'::character varying])::text[])),
    created_date            timestamp(6),
    last_modified_date      timestamp(6),
    created_by              varchar(255),
    updated_by              varchar(255),
    attribute_definition_id bigint,
    primary key (module_name, org_id, rule, rule_name, scope)
    );



create table if not exists selector_and_cost_itinerary_mapping
(
    id                 bigint generated by default as identity
    primary key,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    created_by         varchar(255),
    updated_by         varchar(255),
    cost_itinerary     varchar(255),
    cost_type          varchar(255),
    org_id             varchar(255),
    selector_cf        varchar(255),
    selector_cf_value  varchar(255)
    );



create index if not exists selector_and_cost_itinerary_id_orgid
    on selector_and_cost_itinerary_mapping (id, org_id);

create table if not exists sourcing_attribute
(
    id                   bigint generated by default as identity
    primary key,
    created_date         timestamp(6),
    last_modified_date   timestamp(6),
    created_by           varchar(255),
    updated_by           varchar(255),
    attribute_name       varchar(255),
    custom_attribute_key varchar(255),
    is_derived           boolean,
    json_path            varchar(255),
    org_id               varchar(255)
    );



create table if not exists sourcing_attributes_definition
(
    id                 bigint generated by default as identity
    primary key,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    created_by         varchar(255),
    updated_by         varchar(255),
    module             varchar(255),
    name               varchar(255),
    opt_attributes     varchar(255),
    org_id             varchar(255),
    req_attributes     varchar(255),
    scope              varchar(255)
    constraint sourcing_attributes_definition_scope_check
    check ((scope)::text = ANY
((ARRAY ['SOURCING_RULE'::character varying, 'OPTIMIZATION'::character varying, 'HOLIDAY_CUTOFF'::character varying, 'ML_RULE'::character varying, 'ML_OVERRIDE_RULE'::character varying, 'TRANSFER_SCHEDULE_RULE'::character varying])::text[])),
    status             varchar(255)
    constraint sourcing_attributes_definition_status_check
    check ((status)::text = ANY
((ARRAY ['ACTIVE'::character varying, 'INACTIVE'::character varying, 'DRAFT'::character varying])::text[]))
    );



create table if not exists sourcing_constraint
(
    id                        bigint generated by default as identity
    primary key,
    created_date              timestamp(6),
    last_modified_date        timestamp(6),
    created_by                varchar(255),
    updated_by                varchar(255),
    group_id                  varchar(255),
    org_id                    varchar(255),
    sourcing_constraint       varchar(255)
    constraint sourcing_constraint_sourcing_constraint_check
    check ((sourcing_constraint)::text = ANY
((ARRAY ['PRE_ORDER_PROMISE_DATE'::character varying, 'SHIP_COMPLETE_LINE'::character varying])::text[])),
    sourcing_constraint_value varchar(255)
    );



create table if not exists sourcing_rule_details
(
    id                 bigint generated by default as identity
    primary key,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    created_by         varchar(255),
    updated_by         varchar(255),
    node_groups        varchar(255),
    org_id             varchar(255),
    sequence           integer,
    sourcing_rule_id   bigint
    );



create table if not exists sourcing_rules_configuration
(
    id                                bigint generated by default as identity
    primary key,
    created_date                      timestamp(6),
    last_modified_date                timestamp(6),
    created_by                        varchar(255),
    updated_by                        varchar(255),
    org_id                            varchar(255),
    sourcing_attributes_definition_id bigint,
    sourcing_rule                     varchar(255),
    sourcing_rule_name                varchar(255)
    );



create index if not exists orgid_sourcingattributesdefinitionid
    on sourcing_rules_configuration (org_id, sourcing_attributes_definition_id);

create table if not exists task_impl_archive
(
    task_id              varchar(255) not null
    primary key,
    created              timestamp(6) with time zone,
                                          created_by           varchar(255),
    tenant               varchar(255),
    updated              timestamp(6) with time zone,
                                          updated_by           varchar(255),
    version              bigint,
    arg_class_name       varchar(255),
    class_name           varchar(255),
    failure_reason       text,
    first_execution_time timestamp(6) with time zone,
                                          last_execution_time  timestamp(6) with time zone,
                                          last_retried_by      varchar(255),
    meta_type            smallint
    constraint task_impl_archive_meta_type_check
    check ((meta_type >= 0) AND (meta_type <= 1)),
    method_arg           text,
    method_name          varchar(255),
    min_execution_time   timestamp(6) with time zone,
                                          object_id            varchar(255),
    object_type          varchar(255),
    partition_key        varchar(255),
    retry_count          integer,
    stack_trace          text,
    task_status          varchar(255)
    constraint task_impl_archive_task_status_check
    check ((task_status)::text = ANY
((ARRAY ['CREATED'::character varying, 'IN_QUEUE'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'CLOSED'::character varying])::text[])),
    task_type            varchar(255),
    topic_name           varchar(255)
    );



create table if not exists task_info_impl
(
    id                               varchar(255) not null
    primary key,
    created                          timestamp(6) with time zone,
                                                      created_by                       varchar(255),
    tenant                           varchar(255),
    updated                          timestamp(6) with time zone,
                                                      updated_by                       varchar(255),
    version                          bigint,
    active                           boolean      not null,
    delay_in_secs                    integer,
    execution_type                   varchar(255)
    constraint task_info_impl_execution_type_check
    check ((execution_type)::text = ANY
((ARRAY ['KAFKA'::character varying, 'TASK_EXECUTOR'::character varying])::text[])),
    initial_delay_in_secs            integer,
    instance_type                    varchar(255),
    type                             smallint
    constraint task_info_impl_type_check
    check ((type >= 0) AND (type <= 2)),
    value                            varchar(255),
    max_tasks                        integer,
    recurring_task_creation_interval integer,
    retry_count                      integer,
    task_running_freq                integer,
    task_type                        varchar(255),
    constraint ukt2y79j42sa32ih5q86iflw7rg
    unique (task_type, tenant)
    );



create table if not exists task_impl
(
    task_id              varchar(255) not null
    primary key,
    created              timestamp(6) with time zone,
                                          created_by           varchar(255),
    tenant               varchar(255),
    updated              timestamp(6) with time zone,
                                          updated_by           varchar(255),
    version              bigint,
    arg_class_name       varchar(255),
    class_name           varchar(255),
    failure_reason       text,
    first_execution_time timestamp(6) with time zone,
                                          last_execution_time  timestamp(6) with time zone,
                                          last_retried_by      varchar(255),
    meta_type            smallint
    constraint task_impl_meta_type_check
    check ((meta_type >= 0) AND (meta_type <= 1)),
    method_arg           text,
    method_name          varchar(255),
    min_execution_time   timestamp(6) with time zone,
                                          object_id            varchar(255),
    object_type          varchar(255),
    partition_key        varchar(255),
    retry_count          integer,
    stack_trace          text,
    task_status          varchar(255)
    constraint task_impl_task_status_check
    check ((task_status)::text = ANY
((ARRAY ['CREATED'::character varying, 'IN_QUEUE'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'CLOSED'::character varying])::text[])),
    task_type            varchar(255),
    topic_name           varchar(255)
    );



create table if not exists tenant_configdata
(
    id                 bigint generated by default as identity
    primary key,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    created_by         varchar(255),
    updated_by         varchar(255),
    config_key         varchar(255),
    config_value       varchar(2000),
    org_id             varchar(255)
    );

insert into tenant_configdata (config_key, config_value, org_id)
values ('buffer-horizon-days', '7', 'NEXTUPLE_GR'),
       ('capacity-enabled', 'true', 'NEXTUPLE_GR'),
       ('capacity-horizon', '7', 'NEXTUPLE_GR'),
       ('event-allowed-pages', '{ExceptionEvent: ERROR}', 'NEXTUPLE_GR'),
       ('event-log-level', '{ExceptionEvent: ERROR}', 'NEXTUPLE_GR'),
       ('event-publish-enabled',
        '{ItemDetailsEvent: false,OrderLinesWithShipNodeIdEvent: false,OrderLineEligibilityEvent: false,EligibleItemNodeTypesEvent: false,InventoryDetailsEvent: false,WeightageDetailsEvent: false,SourcingSolutionEvent: false,SuggestedPromiseEvent: true,TransitDetailsEvent: false, ReservationRequestEvent: false,ReservationResponseEvent: false,NodeCarrierPriorityEvent:false}',
        'NEXTUPLE_GR'),
       ('final-solutions-cap', '10', 'NEXTUPLE_GR'),
       ('line-solutions-required', '1000', 'NEXTUPLE_GR'),
       ('line-threshold', '10', 'NEXTUPLE_GR'),
       ('log-suppression-service-options', 'cart,checkout,billing,orderreview', 'NEXTUPLE_GR'),
       ('max-solutions', '1000000', 'NEXTUPLE_GR'),
       ('node-types', 'STORE,MFC,DC,FC', 'NEXTUPLE_GR'),
       ('processing-time-computation', 'ADDITION', 'NEXTUPLE_GR'),
       ('service-option-inventory-type-mapping', 'SDND:PICK,EXPRESS:SHIP,STANDARD:SHIP,BOPIS:PICK,NEXTDAY:SHIP',
        'NEXTUPLE_GR'),
       ('service-options', 'EXPRESS,STANDARD,SDND,NEXTDAY', 'NEXTUPLE_GR'),
       ('sourcing-no-of-solution', '3', 'NEXTUPLE_GR'),
       ('top-solutions-count', '10', 'NEXTUPLE_GR');

create table if not exists tenant_cost_type
(
    id                 bigint generated by default as identity
    primary key,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    created_by         varchar(255),
    updated_by         varchar(255),
    cost_type          varchar(255),
    display_name       varchar(255),
    label              smallint
    constraint tenant_cost_type_label_check
    check ((label >= 0) AND (label <= 1)),
    org_id             varchar(255)
    );



create index if not exists tenant_cost_type_id_orgid
    on tenant_cost_type (id, org_id);

create table if not exists transit_buffer_config_request
(
    id                         bigint generated by default as identity
    primary key,
    created_date               timestamp(6),
    last_modified_date         timestamp(6),
    created_by                 varchar(255),
    updated_by                 varchar(255),
    buffer_days                double precision,
    carrier_service_id         varchar(255),
    download_file_meta_data_id bigint,
    end_date                   timestamp(6),
    file_meta_data_id          bigint,
    org_id                     varchar(255),
    parent_request_id          bigint,
    start_date                 timestamp(6),
    status                     varchar(255)
    constraint transit_buffer_config_request_status_check
    check ((status)::text = ANY
((ARRAY ['CREATED'::character varying, 'INPROGRESS'::character varying, 'COMPLETED'::character varying, 'DELETED'::character varying, 'INACTIVE'::character varying, 'ERROR'::character varying])::text[]))
    );



create table if not exists transit_buffer_data
(
    carrier_service_id               varchar(255) not null,
    destination_geozone              varchar(255) not null,
    org_id                           varchar(255) not null,
    source_geozone                   varchar(255) not null,
    created_date                     timestamp(6),
    last_modified_date               timestamp(6),
    created_by                       varchar(255),
    updated_by                       varchar(255),
    buffer_days                      double precision,
    buffer_end_date                  timestamp(6),
    buffer_start_date                timestamp(6),
    transit_buffer_config_request_id bigint,
    primary key (carrier_service_id, destination_geozone, org_id, source_geozone)
    );



create index if not exists transitbufferconfigrequestid_key
    on transit_buffer_data (transit_buffer_config_request_id);

create table if not exists transit_buffer_req_jobs_reference
(
    id                    bigint generated by default as identity
    primary key,
    created_date          timestamp(6),
    last_modified_date    timestamp(6),
    created_by            varchar(255),
    updated_by            varchar(255),
    action                smallint
    constraint transit_buffer_req_jobs_reference_action_check
    check ((action >= 0) AND (action <= 2)),
    ext_reference_id      varchar(255),
    transit_buffer_req_id bigint
    );



create index if not exists extreferenceid_key
    on transit_buffer_req_jobs_reference (ext_reference_id);

create table if not exists transit_buffers_data
(
    id                               bigint generated by default as identity
    primary key,
    created_date                     timestamp(6),
    last_modified_date               timestamp(6),
    created_by                       varchar(255),
    updated_by                       varchar(255),
    buffer_days                      double precision,
    buffer_end_date                  timestamp(6),
    buffer_start_date                timestamp(6),
    carrier_service_id               varchar(255),
    destination_geozone              varchar(255),
    org_id                           varchar(255),
    source_geozone                   varchar(255),
    transit_buffer_config_request_id bigint
    );



create index if not exists buffers_orgid_dest_src_carrier_index
    on transit_buffers_data (org_id, destination_geozone, source_geozone, carrier_service_id);

create table if not exists transit_data
(
    carrier_service_id  varchar(255) not null,
    destination_geozone varchar(255) not null,
    org_id              varchar(255) not null,
    source_geozone      varchar(255) not null,
    created_date        timestamp(6),
    last_modified_date  timestamp(6),
    created_by          varchar(255),
    updated_by          varchar(255),
    buffer_days         double precision,
    buffer_end_date     timestamp(6),
    buffer_start_date   timestamp(6),
    transit_days        real,
    primary key (carrier_service_id, destination_geozone, org_id, source_geozone)
    );



create table if not exists user_exit_config
(
    id                  bigint generated by default as identity
    primary key,
    created_date        timestamp(6),
    last_modified_date  timestamp(6),
    created_by          varchar(255),
    updated_by          varchar(255),
    app_name            varchar(255),
    attribute_json_path varchar(255),
    org_id              varchar(255),
    propagate_error     boolean,
    service_name        varchar(255),
    ue_impl_type        smallint
    constraint user_exit_config_ue_impl_type_check
    check ((ue_impl_type >= 0) AND (ue_impl_type <= 1)),
    url                 varchar(255),
    user_exit_name      varchar(255),
    constraint ukf7q34s4yqau8kssp0269uedj5
    unique (user_exit_name, app_name, org_id, service_name)
    );



create table if not exists user_exit_metadata
(
    id                     bigint generated by default as identity
    primary key,
    created_date           timestamp(6),
    last_modified_date     timestamp(6),
    created_by             varchar(255),
    updated_by             varchar(255),
    app_name               varchar(255),
    description            varchar(255),
    execution_failure_type smallint
    constraint user_exit_metadata_execution_failure_type_check
    check ((execution_failure_type >= 0) AND (execution_failure_type <= 1)),
    name                   varchar(255),
    post_ue_name           varchar(255),
    pre_ue_name            varchar(255),
    service_name           varchar(255),
    type                   smallint
    constraint user_exit_metadata_type_check
    check ((type >= 0) AND (type <= 1)),
    constraint ukghu1s6ai18hh0s6rdjv0amfc2
    unique (name, app_name, service_name)
    );



create table if not exists weightage_configuration
(
    key                varchar(255) not null,
    org_id             varchar(255) not null,
    type               varchar(255) not null,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    created_by         varchar(255),
    updated_by         varchar(255),
    weightage          real,
    primary key (key, org_id, type)
    );



create index if not exists orgid_type_key
    on weightage_configuration (org_id, type, key);

create table if not exists zones
(
    carrier_service_id  varchar(255) not null,
    destination_geozone varchar(255) not null,
    org_id              varchar(255) not null,
    source_geozone      varchar(255) not null,
    created_date        timestamp(6),
    last_modified_date  timestamp(6),
    created_by          varchar(255),
    updated_by          varchar(255),
    zone                varchar(255),
    primary key (carrier_service_id, destination_geozone, org_id, source_geozone)
    );



create index if not exists orgid_destinationgeozone
    on zones (org_id, destination_geozone);

create table if not exists transfer_schedules
(
    id                 bigint generated by default as identity
    primary key,
    created_date       timestamp(6),
    last_modified_date timestamp(6),
    created_by         varchar(255),
    updated_by         varchar(255),
    dropoff_node_id    varchar(255),
    end_time           timestamp(6),
    org_id             varchar(255),
    rule               varchar(255),
    rule_name          varchar(255),
    source_node_id     varchar(255),
    start_time         timestamp(6)
    );

create index if not exists org_source_dropoff_index
    on transfer_schedules (org_id, source_node_id, dropoff_node_id);

