spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: abhishek

logging:
  level:
    com.nextuple: DEBUG