name: reusable-workflow

on:
  workflow_dispatch:
    inputs:
      module:
        description: Enter root directory
        type: string
        required: true
  workflow_call:
    inputs:
      module:
        required: true
        type: string
jobs:

  Build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      issues: read
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
      - uses: aws-actions/setup-sam@v1
      - uses: azure/setup-kubectl@v2.0
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: git-actions-pipeline
          aws-region: us-east-1
      - name: Build Analyze & Publish Snapshot
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain hbc --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} --query authorizationToken --output text`
          bash ./gradlew -Pbuild_target=SNAPSHOT clean build jacocoTestReport spotlessApply spotbugsMain publish -p ${{ inputs.module }}
          bash ./gradlew -Pbuild_target=SNAPSHOT -Dsonar.login=$SONAR_TOKEN sonarqube showSonarQubeLink --info