name: PR-CALENDAR

on:
  workflow_call:
  pull_request:
    paths:
      - "calendar/**"
    branches: [ devr3, hotfix ]

jobs:
  PR-Analysis:
    name: R3
    uses: ./.github/workflows/pr-flow.yml
    with:
      module: calendar
    secrets: inherit