name: CALENDAR BUILD-DEPLOY

on:
  push:
    branches: [ pe-config-v1 ]
    paths:
      - "calendar/**"

jobs:

  Build-Deploy:
    uses: ./.github/workflows/build&deploy.yml
    with:
      module: master-data
    secrets: inherit




