name: CALENDAR BUILD-DEPLOY

on:
  push:
    branches: [ pe-config-v2 ]
    paths:
      - "calendar/**"
      - ".github/workflows/calendar-buildDeploy.yml"

jobs:

  Build-Deploy:
    uses: ./.github/workflows/build&deploy.yml
    with:
      module: calendar
    secrets: inherit




