name: PR-CALENDAR

on:
  workflow_call:
  pull_request:
    paths:
      - "calendar/**"
    branches: [ pe-config-v2 ]

jobs:
  PR-Analysis:
    uses: ./.github/workflows/pr-flow.yml
    with:
      module: calendar
    secrets: inherit