name: CALENDAR BUILD-DEPLOY

on:
  push:
    branches: [ devr3 ]
    paths:
      - "calendar/**"
      - "deploy-scripts/**"
      - "manifests/**"
      - ".github/**"
jobs:

  Build-Deploy:
    name: R3
    uses: ./.github/workflows/build&deploy.yml
    with:
      module: calendar
    secrets: inherit




