name: PR-CARRIER

on:
  workflow_call:
  pull_request:
    paths:
      - "carrier/**"
    branches: [ development, hotfix ]

jobs:
  PR-Analysis:
    uses: ./.github/workflows/pr-flow.yml
    with:
      module: carrier
    secrets: inherit