name: CARRIER BUILD-DEPLOY

on:
  push:
    branches: [ development ]
    paths:
      - "carrier/**"
     
jobs:
  Build-Deploy:
    uses: ./.github/workflows/build&deploy.yml
    with:
      module: carrier
    secrets: inherit




