name: PR-CARRIER

on:
  workflow_call:
  pull_request:
    paths:
      - "carrier/**"
    branches: [ devr3, hotfix ]

jobs:
  PR-Analysis:
    name: R3
    uses: ./.github/workflows/pr-flow.yml
    with:
      module: carrier
    secrets: inherit