name: COMMON-UTIL BUILD

on:
  push:
    branches: [ development, hotfix ]
    paths:
      - "common-util/**"
      - "build.gradle"
jobs:

  Build-Publish:
    uses: ./.github/workflows/build.yml
    with:
      module: common-util
    secrets: inherit




