name: PR-COMMON

on:
  workflow_call:
  pull_request:
    paths:
      - "common/**"
    branches: [ devr3, hotfix ]

jobs:
  PR-Analysis:
    name: R3
    uses: ./.github/workflows/pr-flow.yml
    with:
      module: common
    secrets: inherit