  name: COMMON-CONFIGURATION BUILD-DEPLOY

on:
  push:
    branches: [ development ]
    paths:
      - "common-configuration/**"
      - "deploy-scripts/**"
      - "manifests/**"
      - ".github/**"
jobs:

  Build-Deploy:
    uses: ./.github/workflows/build&deploy.yml
    with:
      module: common-configuration
    secrets: inherit




