name: CSV-UTILITY HOTFIX

on:
  push:
    branches: [ hotfix ]
    paths:
      - "csv-utility/**"
      - "deploy-scripts/**"
      - "manifests/**"
      - ".github/**"
jobs:

  Build-Deploy:
    uses: ./.github/workflows/Build&Deploy_Hotfix.yml
    with:
      module: csv-utility
    secrets: inherit




