name: CSV-UTILITY BUILD-DEPLOY

on:
  push:
    branches: [ development ]
    paths:
      - "csv-utility/**"
      - "deploy-scripts/**"
      - "manifests/**"
      - ".github/**"
     
jobs:
  Build-Deploy:
    uses: ./.github/workflows/build&deploy.yml
    with:
      module: csv-utility
    secrets: inherit




