name: PR-DATA-UPLOAD

on:
  workflow_call:
  pull_request:
    paths:
      - "data-upload/**"
    branches: [ development, hotfix ]

jobs:
  PR-Analysis:
    uses: ./.github/workflows/pr-flow.yml
    with:
      module: data-upload
    secrets: inherit