name: DATA-UPLOAD BUILD-DEPLOY

on:
  push:
    branches: [ development ]
    paths:
      - "data-upload/**"
      - "deploy-scripts/**"
      - "manifests/**"
      - ".github/**"
     
jobs:
  Build-Deploy:
    uses: ./.github/workflows/build&deploy.yml
    with:
      module: data-upload
    secrets: inherit




