name: PR-GLOBAL-CONFIGURATION

on:
  workflow_call:
  pull_request:
    paths:
      - "global-configuration/**"
    branches: [ development, hotfix ]

jobs:
  PR-Analysis:
    uses: ./.github/workflows/pr-flow.yml
    with:
      module: global-configuration
    secrets: inherit