name: ITEM BUILD-DEPLOY

on:
  push:
    branches: [ development ]
    paths:
      - "item/**"
      - ".github/workflows/build&deploy.yml"
jobs:
  Build-Deploy:
    uses: ./.github/workflows/build&deploy.yml
    with:
      module: item
    secrets: inherit




