name: ITEM BUILD-DEPLOY

on:
  push:
    branches: [ development ]
    paths:
      - "item/**"
      - "node/**"
      - "deploy-scripts/**"
      - "manifests/**"
      - ".github/**"
     
jobs:
  Build-Deploy:
    uses: ./.github/workflows/build&deploy.yml
    with:
      module: item
    secrets: inherit




