name: PR-JOBS-CONSUMER

on:
  workflow_call:
  pull_request:
    paths:
      - "jobs-consumer/**"
    branches: [ development, hotfix ]

jobs:
  PR-Analysis:
    uses: ./.github/workflows/pr-flow.yml
    with:
      module: jobs-consumer
    secrets: inherit