name: MASTER-DATA BUILD-DEPLOY

on:
  push:
    branches: [ pe-config-draft ]
    paths:
      - "initial/**"
      - ".github/workflows/build&deploy.yml"

jobs:

  Build-Deploy:
    uses: ./.github/workflows/build&deploy.yml
    with:
      module: master-data
    secrets: inherit




