name: MASTER-DATA BUILD-DEPLOY

on:
  push:
    branches: [ pe-config-v2 ]
    paths:
      - "master-data/**"
      - ".github/workflows/masterData-buildDeploy.yml"
jobs:

  Build-Deploy:
    uses: ./.github/workflows/build&deploy.yml
    with:
      module: master-data
    secrets: inherit




