name: NFS-COMMON BUILD

on:
  push:
    branches: [ development ]
    paths:
      - "nfs-common/**"
      - ".github/workflows/nfs-common-build.yml"
jobs:

  Build-Publish:
    uses: ./.github/workflows/build.yml
    with:
      module: nfs-common
    secrets: inherit




