name: NFS-COMMON BUILD

on:
  push:
    branches: [ pe-config-v2 ]
    paths:
      - "common-util/**"
      - ".github/workflows/nfs-common-build.yml"

jobs:

  Build-Publish:
    uses: ./.github/workflows/build.yml
    with:
      module: nfs-common
    secrets: inherit




