name: NFS-COMMON BUILD

on:
  push:
    branches: [ development ]
    paths:
      - "common-util/**"
jobs:

  Build-Publish:
    uses: ./.github/workflows/build.yml
    with:
      module: nfs-common
    secrets: inherit




