name: NODE-CARRIER RELEASE

on:
  push:
    tags:
      - '*RELEASE'
     
jobs:
  Build-Deploy:
    uses: ./.github/workflows/release-flow.yml
    with:
      module: node-carrier
    secrets: inherit




