name: HOTFIX BUILD-DEPLOY

on:
  push:
    branches: [ hotfix ]
    paths:
      - "node-carrier/**"
      - "deploy-scripts/**"
      - "manifests/**"
      - ".github/**"
     
jobs:
  Build-Deploy:
    uses: ./.github/workflows/Build&Deploy_Hotfix.yml
    with:
      module: node-carrier
    secrets: inherit




