name: PR-NODE

on:
  workflow_call:
  pull_request:
    paths:
      - "node/**"
    branches: [ devr3, hotfix ]

jobs:
  PR-Analysis:
    name: R3
    uses: ./.github/workflows/pr-flow.yml
    with:
      module: node
    secrets: inherit