name: NODE BUILD-DEPLOY

on:
  push:
    branches: [ devr3 ]
    paths:
      - "node/**"
      - "deploy-scripts/**"
      - "manifests/**"
      - ".github/**"
     
jobs:
  Build-Deploy:
    name: R3
    uses: ./.github/workflows/build&deploy.yml
    with:
      module: node
    secrets: inherit




