name: NODE-CARRIER BUILD-DEPLOY

on:
  push:
    branches: [ development ]
    paths:
      - "node-carrier/**"
      - "deploy-scripts/**"
      - "manifests/**"
      - ".github/**"
     
jobs:
  Build-Deploy:
    uses: ./.github/workflows/build&deploy.yml
    with:
      module: node-carrier
    secrets: inherit




