name: PR-POSTAL-CODE-TIMEZONE

on:
  workflow_call:
  pull_request:
    paths:
      - "postal-code-timezone/**"
    branches: [ pe-config-v2 ]

jobs:
  PR-Analysis:
    uses: ./.github/workflows/pr-flow.yml