name: PR-POSTAL-CODE-TIMEZONE

on:
  workflow_call:
  pull_request:
    paths:
      - "postal-code-timezone/**"
    branches: [ devr3, hotfix ]

jobs:
  PR-Analysis:
    name: R3
    uses: ./.github/workflows/pr-flow.yml
    with:
      module: postal-code-timezone
    secrets: inherit