name: POSTAL-CODE-TIMEZONE BUILD-DEPLOY

on:
  push:
    branches: [ pe-config-v2 ]
    paths:
      - "postal-code-timezone/**"
      - ".github/workflows/postal-code-timezone-buildDeploy.yml"
jobs:
  Build-Deploy:
    uses: ./.github/workflows/build&deploy.yml
    with:
      module: postal-code-timezone
    secrets: inherit




