name: POSTAL-CODE-TIMEZONE BUILD-DEPLOY

on:
  push:
    branches: [ development ]
    paths:
      - "postal-code-timezone/**"
      - "deploy-scripts/**"
      - "manifests/**"
      - ".github/workflows/build&deploy.yml"
jobs:
  Build-Deploy:
    uses: ./.github/workflows/build&deploy.yml
    with:
      module: postal-code-timezone
    secrets: inherit




