name: POSTAL-CODE-TIMEZONE BUILD-DEPLOY

on:
  push:
    branches: [ devr3 ]
    paths:
      - "postal-code-timezone/**"
      - "deploy-scripts/**"
      - "manifests/**"
      - ".github/**"
jobs:
  Build-Deploy:
    name: R3
    uses: ./.github/workflows/build&deploy.yml
    with:
      module: postal-code-timezone
    secrets: inherit




