name: PROMISE-SOURCING-RULE RELEASE

on:
  push:
    tags:
      - '*RELEASE'
jobs:

  Build-Deploy:
    uses: ./.github/workflows/release-flow.yml
    with:
      module: promise-sourcing-rule
    secrets: inherit




