name: PR-PROMISE-SOURCING-RULE

on:
  workflow_call:
  pull_request:
    paths:
      - "promise-sourcing-rule/**"
    branches: [ development, hotfix ]

jobs:
  PR-Analysis:
    uses: ./.github/workflows/pr-flow.yml
    with:
      module: promise-sourcing-rule
    secrets: inherit