name: PROMISE-SOURCING-RULE BUILD-DEPLOY

on:
  push:
    branches: [ pe-config-v2 ]
    paths:
      - "promise-sourcing-rule/**"
      - ".github/workflows/promising-source-rule-buildDeploy.yml"

jobs:

  Build-Deploy:
    uses: ./.github/workflows/build&deploy.yml
    with:
      module: promise-sourcing-rule
    secrets: inherit




