name: PROMISE-SOURCING-RULE HOTFIX

on:
  push:
    branches: [ hotfix ]
    paths:
      - "promise-sourcing-rule/**"
      - "deploy-scripts/**"
      - "manifests/**"
      - ".github/**"
jobs:

  Build-Deploy:
    uses: ./.github/workflows/Build&Deploy_Hotfix.yml
    with:
      module: promise-sourcing-rule
    secrets: inherit




