name: PROMISE-SOURCING-RULE BUILD-DEPLOY

on:
  push:
    branches: [ development ]
    paths:
      - "promise-sourcing-rule/**"
      - "deploy-scripts/**"
      - "manifests/**"
      - ".github/**"
jobs:

  Build-Deploy:
    uses: ./.github/workflows/build&deploy.yml
    with:
      module: promise-sourcing-rule
    secrets: inherit




