name: PR-SERVICE-INVENTORY

on:
  workflow_call:
  pull_request:
    paths:
      - "service-inventory/**"
    branches: [ devr3, hotfix ]

jobs:
  PR-Analysis:
    name: R3
    uses: ./.github/workflows/pr-flow.yml
    with:
      module: service-inventory
    secrets: inherit