name: SERVICE-INVENTORY HOTFIX

on:
  push:
    branches: [ hotfix ]
    paths:
      - "service-inventory/**"
      - "deploy-scripts/**"
      - "manifests/**"
      - ".github/**"
     
jobs:
  Build-Deploy:
    uses: ./.github/workflows/Build&Deploy_Hotfix.yml
    with:
      module: service-inventory
    secrets: inherit




