name: SERVICE-INVENTORY BUILD-DEPLOY

on:
  push:
    branches: [ development ]
    paths:
      - "service-inventory/**"
      - ".github/workflows/build&deploy.yml"
jobs:
  Build-Deploy:
    uses: ./.github/workflows/build&deploy.yml
    with:
      module: service-inventory
    secrets: inherit




