name: TRANSIT BUILD-DEPLOY

on:
  push:
    branches: [ development ]
    paths:
      - "transit/**"
     
jobs:
  Build-Deploy:
    uses: ./.github/workflows/build&deploy.yml
    with:
      module: transit
    secrets: inherit




