name: PR-TRANSIT

on:
  workflow_call:
  pull_request:
    paths:
      - "transit/**"
    branches: [ development, hotfix ]

jobs:
  PR-Analysis:
    uses: ./.github/workflows/pr-flow.yml
    with:
      module: transit
    secrets: inherit