name: WEIGHTAGE-CONFIGURATION BUILD-DEPLOY

on:
  push:
    branches: [ development ]
    paths:
      - "weightage-configuration/**"
jobs:

  Build-Deploy:
    uses: ./.github/workflows/build&deploy.yml
    with:
      module: weightage-configuration
    secrets: inherit




