name: PR-WEIGHTAGE-CONFIGURATION

on:
  workflow_call:
  pull_request:
    paths:
      - "weightage-configuration/**"
    branches: [ pe-config-v2 ]

jobs:
  PR-Analysis:
    uses: ./.github/workflows/pr-flow.yml
    with:
      module: weightage-configuration
    secrets: inherit