name: PR-WEIGHTAGE-CONFIGURATION

on:
  workflow_call:
  pull_request:
    paths:
      - "weightage-configuration/**"
    branches: [ devr3, hotfix ]

jobs:
  PR-Analysis:
    name: R3
    uses: ./.github/workflows/pr-flow.yml
    with:
      module: weightage-configuration
    secrets: inherit