name: PR-WEIGHTAGE-CONFIGURATION

on:
  workflow_call:
  pull_request:
    paths:
      - "weightage-configuration/**"
    branches: [ development ]

jobs:
  PR-Analysis:
    uses: ./.github/workflows/pr-flow.yml