name: WEIGHTAGE-CONFIGURATION BUILD-DEPLOY

on:
  push:
    branches: [ pe-config-v2 ]
    paths:
      - "weightage-configuration/**"
      - ".github/workflows/weightage-configuration-buildDeploy.yml"
jobs:

  Build-Deploy:
    uses: ./.github/workflows/build&deploy.yml
    with:
      module: weightage-configuration
    secrets: inherit




